### ISSUE TITLE
Method to Save the Version Name

### ISSUE THREAD

**Issue by nicknnator** [Esri/local-government-desktop-addins#1]
There is not a method to save the version name.  This would be good to have in case someone has multiple versions they can use to edit to track down which version was used to make the edits.
Thanks!

**Comment by MikeMillerGIS** [comment]
This method is now exposed in the MAP_INFO function

**Comment by MikeMillerGIS** [comment]
https://github.com/Esri/local-government-desktop-addins/issues/131

**Comment by pLeBlanc93** [comment]
documented new method
