### ISSUE TITLE
BUG-000095060  Attribute assistant fails to auto-populate a certain feature class for value method 'Intersecting_Feature' in a Windows 10 environment.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#101]
<div><div>
<span><b>Salesforce ID:</b> BUG-000095060</span><br/>
<span><b>Salesforce Submitter:</b> Aarthi Dwarakanath</span><br/>
<span><b>Salesforce Submit Date:</b> 3/17/2016 3:52 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000095060</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.3.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Fix has already been implemented in the dev branch of the code.</span><br/>
</div></div>
<span><b>Salesforce ID:</b> BUG-000096261</span><br/>

**Comment by LindsayThomas** [comment]
A resolution to a bug, causing the “Intersecting Feature” method to fail on Window 10 operating systems.

**Comment by MikeMillerGIS** [comment]
The issue really had nothing to do with the O/S.  It was a spatial reference issue.  The tools were using the spatial reference tolerance to generate an area to search.  This caused a collapsed polygon in certain situations.  The spatial reference tolerance was swapped out to use the Maps search tolerance.

**Comment by MikeMillerGIS** [comment]
Fix deployed as part of 6-14-2016 add in
