### ISSUE TITLE
"Add a Point and split an intersecting line" Construction Tool does not refresh map display

### ISSUE THREAD

**Issue by MikeQuartic** [Esri/local-government-desktop-addins#104]
When using the "Add a Point and split an intersecting line" Construction Tool, the junction is added, and the edge is split, but the junction is not displayed on the map.  The editor has to click the "Refresh" button or hit F5 to see it.  Is there a way to have the map display automatically refresh and show the newly added Junction w/o having to go through an extra step?

I'm using ArcGIS for Desktop 10.3.1 and version 6.26.2015 for Water Utility for Network Tools Add-In

**Comment by MikeMillerGIS** [comment]
I added the fix, it will make the next release.

**Comment by pLeBlanc93** [comment]
verified refresh
