### ISSUE TITLE
BUG-000095522  In the Attribute Assistant, please expose a property on the Create Linked Records method to save the new record immediately so that rules, which are yet to process, can access that record.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#105]
<div><div>
<span><b>Salesforce ID:</b> BUG-000095522</span><br/>
<span><b>Salesforce Submitter:</b> Barbara Sieg</span><br/>
<span><b>Salesforce Submit Date:</b> 4/05/2016 9:24 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Performance</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000095522</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.3</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Code checked in to resolve issue and hotfix being worked on</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
Installed in dev branch

**Comment by LindsayThomas** [comment]
For the Create Linked Record – Add |True to the end of the rule.  This last parameter is optional and by default the new record is not posted to the GDB until all the rules for the edited feature are processed.  By adding TRUE, the data is stored, so any proceeding rule is processed.  
RelatedInfo|FIPS|FIPS|FIPS|FIPS
To 
RelatedInfo|FIPS|FIPS|FIPS|FIPS|TRUE

**Comment by LindsayThomas** [comment]
RNote- A resolution to a bug, supporting the “Create Linked Record” method to save new records immediately, allowing rules that have not been triggered to access the record.

**Comment by MikeMillerGIS** [comment]
Fix deployed as part of 6-14-2016 add in
