### ISSUE TITLE
Water Utility Profile graph labels

### ISSUE THREAD

**Issue by klaughead** [Esri/local-government-desktop-addins#106]
I'm currently working with the Water Utility profile tool and was wondering if anyone had worked with labeling. I'm looking to be able to label manholes (points) as well as format the main (line) labels a bit differently. Is there a way to do this or are we stuck with single labels on the mains?

**Comment by MikeMillerGIS** [comment]
The only settings in the config are you can add any number of 
 <Line_Label>DIAMETER</Line_Label> sections to add more fields to the label.  Other than that, you have to modify the result after the tool creates it
