### ISSUE TITLE
BUG-000095214  When an apostrophe is present in the source field key value, the Attribute Assistant COPY_LINKED_RECORD method does not work.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#107]
<div><div>
<span><b>Salesforce ID:</b> BUG-000095214</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 3/23/2016 11:06 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000095214</span><br/>
<span><b>Work Around:</b> Instead of using key fields with values containing apostrophes, create new key fields and calculate those to remove apostrophes. 

For example, use an EXPRESSION method to remove any apostrophes:
Replace( [ROAD_NAME_FULL], "'", " ")

When the new key fields are used in the COPY_LINKED_RECORD method, everything should succeed because there are no apostrophes in the key fields.</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> We look at fixing for the next release</span><br/>
</div></div>

**Comment by chris-fox** [comment]
Resolved

**Comment by MikeMillerGIS** [comment]
Fix deployed as part of 6-14-2016 add in
