### ISSUE TITLE
BUG-000095365  The Field method in Attribute Assistant 2.25.2016 does not work on a table; it only works for feature classes.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#109]
<div><div>
<span><b>Salesforce ID:</b> BUG-000095365</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 3/29/2016 2:27 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000095365</span><br/>
<span><b>Work Around:</b> Create a table from the domain and use the Copy_Linked_Record method to populate the desired field in the target table from the linked table's description.</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.2.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Issue identified and will provide a fix in the next release</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
A resolution to a bug, causing the “field” method to fail on a standalone table.

**Comment by MikeMillerGIS** [comment]
Fix deployed as part of 6-14-2016 add in
