### ISSUE TITLE
CIP Point Count

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#115]
@MikeMillerGIS 

Point Count not being calculated for projects. Workflow done on both 10.2.1 and 10.4. 
- Create new project
- Select existing service points.
- Also tried with sketch in service connection points.
- Add any other assets to a project
- Save selected assets to the project
- View attributes of the CIP Project Overviews, Point Count was equal to 0 though points were added to the project

**Comment by MikeMillerGIS** [comment]
made the fix, updated add in on mrhyde, please verify

**Comment by clareprice** [comment]
@MikeMillerGIS Verified. Closing issue.
