### ISSUE TITLE
Enhancement - Change Operable Status of Valve

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#116]
When using the "change operable status of valve" tool, when the trace result is returned new features are on top of the valve. In order to use the tool after doing an isolation trace, the user needs to turn off the visibility of the trace results (or of multiple trace results), then use the tool. It would be nice if it could automatically look for the valve feature even if the valve layer is not the top most layer.

@MikeMillerGIS

**Comment by MikeMillerGIS** [comment]
Please verify, updated add ins on mrhyde

**Comment by clareprice** [comment]
@MikeMillerGIS Seems that there is no error message presented if trying to use the tool not in an edit session. Should the "must be editing" error message be for this tool as well?

**Comment by MikeMillerGIS** [comment]
Lets add an enhancement for next release

**Comment by clareprice** [comment]
Ok. Closing this issue and will create a new for the next release. Thanks Mike!
