### ISSUE TITLE
Error Message - Change Operable Status of Valve

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#117]
When using the Change Operable Status of Valve and not in an editing session, no error message is presented but the tool icon does grey out. Would be good to add in the generic "Must be editing to use this tool" message that is in other tools on the toolbars.

**Comment by SASrinivas** [comment]
Doesn't look like this has been addressed. Also, even when in an Edit session, the Operable field isn't getting updated. Tried the config file with both Operable and OPERABLE.

**Comment by MikeMillerGIS** [comment]
@SASrinivas What was not working, this is a tool, you have to click on the valve, not just select a valve and click the tool.  It is working for me

**Comment by SASrinivas** [comment]
Sorry Mike, my bad. I was doing it the other way. Selecting the Valve and then clicking the button. Perhaps we should add the workflow in the documentation.
Also, should this tool be part of the Editing Toolbar (since we are editing the attribute) or is it ok where it is now?

**Comment by MikeMillerGIS** [comment]
It is related to tracing, so I will leave it there for now.  

@pLeBlanc93 doc?

**Comment by pLeBlanc93** [comment]
`Change Operable Status of a Valve` 	Changes the status of a valve from operable to non-operable. **When this tool is enabled, select a valve to change its status.** You can configure the operable and non-operable field in the configuration file.
