### ISSUE TITLE
Add-in categories

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#120]
@MikeMillerGIS @LindsayThomas Noticed with the CIP add-in that the category is "Resource Center Template" 
![image](https://cloud.githubusercontent.com/assets/5611508/15977456/b7025c52-2f0d-11e6-8de3-d1b70efbaca8.png)

For the next release could we update the category for this and other add-ins to sync up?

**Comment by LindsayThomas** [comment]
This would require a rebuild and resigning. I think we should wait for next release. 

Does that work?

@clareprice 
FYI @MikeMillerGIS

**Comment by MikeMillerGIS** [comment]
Yes, I am actually thinking it might be time to put theses in mature.  We have not done a code change in soo long

@hCrothers What do you think?

**Comment by clareprice** [comment]
@LindsayThomas See original comment. Next release would be good.

**Comment by LindsayThomas** [comment]
@clareprice I read Next Release as This Release. ugh

@ScottOppmann are we still shipping CIP addin's?

**Comment by ScottOppmann** [comment]
Nope.  Only in Water Utility solutions I believe.

**Comment by clareprice** [comment]
@MikeMillerGIS Verified. Closing issue.
