### ISSUE TITLE
Attribute-Assistant: Intersect Count doesn't update correctly when point moved participates in geometric network

### ISSUE THREAD

**Issue by roemhildtg** [Esri/local-government-desktop-addins#122]
I've been experimenting with this tool and so far so good, but in one case, I have a geometric network consisting of storm sewer lines and storm structure points at each line endpoint.

I have a field `storm_structure.number_inverts` which represents the number of lines intersecting each point. When I move a point, the geometric network updates, but the value of the number_inverts gets set to 0.

How can I handle this correctly?

**Comment by MikeMillerGIS** [comment]
I believe there is no fix for this as the point edit completes, triggering the AA.  Then the geometric network updates, moving the line.  We just add some new trigger rules, you could use them on the line to trigger the aa in the point once the line moves.


Sent from my Verizon Wireless 4G LTE DROID

**Comment by roemhildtg** [comment]
Okay, so what you're suggesting would look like this:

1. Monitor the line feature class for geometry changes and when that happens,
2. Trigger change on point feature class
3. AA updates field

It would be useful to have triggers like that, like when one feature class changes, trigger a type of change on another feature class, I'm guessing that would look something like this:

Table name: storm_pipe (table to watch for changes)
Field name: null
Value Method: TRIGGER_GEOM_CHANGE
Value Info: storm_struc (table to trigger geometry change)
...etc

**Comment by roemhildtg** [comment]
Maybe I'm misunderstanding, is this already available using one of the rules like **Trigger Attribute Assistant Event Intersecting Feature**?

**Comment by MikeMillerGIS** [comment]
Yes, they were added in the last release

**Comment by roemhildtg** [comment]
I've applied a trigger `TRIGGER_AAEVENT_INTERSECTING_FEATURE`to my line features (storm_pipe) and I set the field to Shape. I set the Value Info to `storm_struc|CHANGEGEO`. 

I have another rule on the storm_struc layer, `INTERSECT_COUNT` with the Value info set to `storm_pipe`. I have this one set to run on create and on geometry change. This rule works correctly when a point is created, but not when the geometry change is "triggered"

Here's the logfile from AA: https://gist.github.com/roemhildtg/fd03664daca6a10cb3cdf726a22f901a#file-gistfile1-txt-L400-L450

According to the log file, it looks like the geometry change is triggering correctly, and the Intersect count rule runs but doesn't find any results for some reason. Any insight on this would be helpful.

**Comment by roemhildtg** [comment]
Okay, I think I understand how its supposed to work now. If I move the storm_struc layer, ArcMap updates the storm pipe geometry to reconnect the network. This was what wasn't working. If, howver, I move the storm pipe endpoint instead, it moves the storm structure point also and it does work correctly. So I'll close this since I have a great workaround.
