### ISSUE TITLE
Manual update not working now with latest June Release

### ISSUE THREAD

**Issue by jayjclark** [Esri/local-government-desktop-addins#124]
The June release fixed the create event from the toolbar, but seems to have broken the manual event.  When selecting features, intersecting features are updated using the create rule, but not with the manual rule.  Before the June fix, the manual events worked but the create event didn't when applying the event for selected features.

**Comment by MikeMillerGIS** [comment]
Jay, we are not able to repo this issue, can you share the schema of your dynamic value table.

**Comment by jayjclark** [comment]
Attached is the schema.  This was also shared

 with Clare Price 


at ESRI.

**Comment by jayjclark** [comment]
Attached is actually the xml file of the dynamic value table.  I couldn't attach it as a zip file or an xml, so it was renamed to .txt.  It needs to be renamed back to an xml file.  I shared the table with Clare at ESRI, so I assume she is working on this too.

[DYNAMICVALUETAB.txt](https://github.com/Esri/local-government-desktop-addins/files/358315/DYNAMICVALUETAB.txt)

**Comment by MikeMillerGIS** [comment]
update release to resolve this issue
