### ISSUE TITLE
Question: Is there a roadmap for these addins?

### ISSUE THREAD

**Issue by roemhildtg** [Esri/local-government-desktop-addins#125]
I am wondering what the future of these addons is since it seems things are migrating to ArcGIS Pro. Will these addins eventually be migrated to pro also?

**Comment by ScottOppmann** [comment]
We are working with the core development team to add "attribute assistant" functionality to ArcGIS and do that at the geodatabase/feature services layer.  That will expose the functionality in ArcGIS Pro, simple web maps, and other ArcGIS apps.  In the meantime, we will continue to support Attribute Assistant and it will be around for quite some time.

**Comment by roemhildtg** [comment]
Thanks for the quick response! That is really good to know, I'll be looking forward to that. Its one of the big hurdles for not switching to Pro at the moment.

**Comment by ScottOppmann** [comment]
Thanks for the feedback and we agree ;)  But will pass your feedback along to the dev team as well.
