### ISSUE TITLE
Enhance the intersecting feature rule to support both the Start and End of lines with a prompt option

### ISSUE THREAD

**Issue by om-henners** [Esri/local-government-desktop-addins#129]
When using the to and from junction field in the attribute assistant, if there are more than one possible result it appears that the attribute assistant will _always_ (regardless of the layer) pick the feature with the lowest OBJECTID.

As a possible feature enhancement, rather than picking the lowest OBJECTID in cases where there is more than one possible result can we get a pop-up window of values for the user to choose from?

**Comment by MikeMillerGIS** [comment]
There is always only one junction at the same location as the network does not support multiple junctions.

**Comment by om-henners** [comment]
Thanks for responding Mike. I realise the network only supports a single junction, but our setup is that there are multiple source feature classes for junctions, and multiple coincident points from candidate feature classes in the one location (points may be retired, other points may be a junction in some cases, and in others represent assets within another junction in others - e.g. a water pressure monitoring meter), i.e. the network in our case is not only conceptual but represents the true spatial location of assets in the network.

Regardless of the status of the point the tool currently selects the point which has the lowest object ID. And while the tool does allow for filtering, it is by a single feature class with a simple equality filter, which means that there may be several assets as candidate junctions at a location. Thus the request for a choice at the time the to/from junction request is fired so you can choose the asset to connect as the junction if there could be more than one choice.

**Comment by MikeMillerGIS** [comment]
You are looking for a different rule then, the to/from junctions use the geometric network to get the junction, and there is always one.

You need to look at the intersecting feature with the S and E flag.  We will need to extend this to also show the prompt.

Is that what you are looking for?

**Comment by om-henners** [comment]
Hi Mike, that would work, yes. Thanks!

**Comment by MikeMillerGIS** [comment]
We can add an enhancement for this.

Sent from my Verizon Wireless 4G LTE DROID

**Comment by MikeMillerGIS** [comment]
Update title to reflect the request.  Thank you for the request.

**Comment by pLeBlanc93** [comment]
Note in the documentation that S/E/SP/EP only works on source lines, not target (intersecting) lines.

**Comment by pLeBlanc93** [comment]
verified new prompt options

**Comment by pLeBlanc93** [comment]
F (Default)	Return the first result found.
P	Present dialog box of intersecting features.
C	Use the centroid as the intersection point, choosing the feature with the lowest objectid.
CP	Use the centroid as the intersection point, presenting a dialog box of intersecting features.
S	Use the start point of the line as the intersection point, choosing the feature with the lowest objectid.
SP	Use the start point of the line as the intersection point, presenting a dialog box of intersecting features.
E	Use the end point of the line as the intersection point, choosing the feature with the lowest objectid.
EP	Use the end point of the line as the intersection point, presenting a dialog box of intersecting features.

It's clearer now how the various `P` options work.
