### ISSUE TITLE
Nearest Feature Attribute - If feature is not found, existing feature values are getting set to defaults

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#130]
Expose option to still support this, but do not change feature by default

**Comment by MikeMillerGIS** [comment]
https://github.com/Esri/local-government-desktop-addins/issues/132

**Comment by pLeBlanc93** [comment]
verified

**Comment by pLeBlanc93** [comment]
## Reset to Default (Optional)	
True	If no feature is found within the specified neighborhood distance, field values will be overwritten with the field's default value.
False (Default)	Field values will not change.
