### ISSUE TITLE
New method to capture document and version properties - MAP_INFO

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#131]

**Comment by MikeMillerGIS** [comment]
Description:  This rule will pull information from the map document or the version info of the layer edited.

**Table Name:** Table or Feature Class to monitor
**Field Name:**  Field to monitor to limit rule to only when field changed, if field is blank, rule is always triggered when
**Value Method**: MAP_INFO
**Value Info:** Field to Store Value in | Value to Store(options:AUTHOR, TITLE, NAME, PATH, VERSION)

**Comment by MikeMillerGIS** [comment]
@pLeBlanc93 new rule

**Comment by pLeBlanc93** [comment]
When accessing properties, check the field length and truncate.
EG my field has length `15` and the title is `25` characters. Only grab the first 15 instead of returning edit error.

**Comment by pLeBlanc93** [comment]
`VERSION` option stores the SDE version you are currently working in

**Comment by MikeMillerGIS** [comment]
VERSION for FileGeoDatbase uses the value of FGDB

**Comment by pLeBlanc93** [comment]
verified

**Comment by MikeMillerGIS** [comment]
Right now, the field name is the field to monitor, the first argument is the field to store the info in, does it make sense to move the first argument to the field name and not have a field to monitor?  This would be more consistent with other rules.

@shoe913 @pLeBlanc93

**Comment by shoe913** [comment]
Personally, I think the more consistent we can make the rules the better. Making the field name the field to update makes alo of sense. 

That being said I also like having the update capability to check changes on a specific field. would it be possible to do something like this?

**Table Name:** Table or Feature Class to monitor
**Field Name:** Field to Store Value in
**Value Method:** MAP_INFO
**Value Info:** Value to Store(options:AUTHOR, TITLE, NAME, PATH, VERSION)|  Field to monitor to limit rule to only when field changed, if field is blank, rule is always triggered (optional)

**Comment by pLeBlanc93** [comment]
multiple methods use field name as the triggering field:

http://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#cascade-attributes
http://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#copy-features
http://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#field-trigger
http://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#previous-value
http://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#update-linked-record
http://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#validate-attribute-lookup
the 5 trigger AA rules

11/68

**Comment by MikeMillerGIS** [comment]
Well, since we are not consistent, leave as is?
