### ISSUE TITLE
ENH-000098013  Make the behavior of the Nearest Feature Attributes rule consistent with other rules

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#132]
<div><div>
<span><b>Salesforce ID:</b> ENH-000098013</span><br/>
<span><b>Salesforce Submitter:</b> Rachel Applebaum</span><br/>
<span><b>Salesforce Submit Date:</b> 7/25/2016 9:18 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\ENH-000098013</span><br/>
<span><b>Work Around:</b> 1. Provide the appropriate/comparable step by step workflow to help illustrate the request.
<ol><li>Open the attached ENHMap.mpk</li><li>Start an editing session and make sure Attribute Assistant is turned on</li><li>Select the Facility Site Point in the middle of the screen and open the attribute editing window</li><li>Run the change rules for selected feature from the Attribute Assistant toolbar
    <ol><li>Note that no feature fall within the 20 ft radius specified by the rule</li></ol>
    </li><li>The FULLADDR field value changes to Null, which is the default value for that layer</li></ol>

<p>If you run the same process with the Nearest Feature rule, where no feature falls within the search radius, the FULLADDR field for the feature would not change. Please make the behavior of the Nearest Feature Attributes rule consistent with the Nearest Feature rule. Tested in 10.2.2 and 10.4.1.</p>
2. What is the problem feature X is trying to solve? (i.e. What is the problem/limitation/design choice that is preventing the customer from moving forward?)<br><br>Two similar rules in Attribute Assistant have different expected behavior. This enhancement would make the expected behavior the same for each rule.<br><br>3. What are the benefits or changes that would result from the enhancement? (i.e. How does making this change help the customer&#39;s workflow or business?)<br><br>Businesses would save time and money as they would not have to search for and fix the attributes of features where they were unexpectedly changed by the Nearest Feature Attributes rule.<br> </span><br/>
<span><b>Product:</b> ArcSDE/Enterprise Geodatabase</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.2.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> We have added a flag to reset the values when not found and by default it mimic nearest feature</span><br/>
</div></div>

**Comment by pLeBlanc93** [comment]
verified
