### ISSUE TITLE
BUG-000097931  Attribute Assistant documentation does not indicate how to create multiple related records.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#134]
<div><div>
<span><b>Salesforce ID:</b> BUG-000097931</span><br/>
<span><b>Salesforce Submitter:</b> Andy Shoemaker</span><br/>
<span><b>Salesforce Submit Date:</b> 7/20/2016 1:29 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Documentation</span><br/>
<span><b>Salesforce Severity:</b> High</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> This is a bug and the same parameter is used for both options.  We will move the Commit.</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
Example of the new help
![image](https://cloud.githubusercontent.com/assets/2707285/17297594/60744ac2-57d4-11e6-9670-c7eb8641cff6.png)

**Comment by pLeBlanc93** [comment]
http://solutionsdev.arcgis.com/shared/help/attribute-assistant/documentation/methods-related-table/#create-linked-record
