### ISSUE TITLE
Enhancement - Expose option to split line at Points Along in Add Laterals functions

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#137]

**Comment by MikeMillerGIS** [comment]
document the following in the help @pLeBlanc93 
<PointsAlong>
        <PointAlong>
<SplitLateral>false</SplitLateral>

and 

      <LateralLine_SplitMain>false</LateralLine_SplitMain>

**Comment by MikeMillerGIS** [comment]
https://github.com/Esri/local-government-desktop-addins/commit/64d56f44fe6e2c3bd3d85e28a121b10a1edd74f5

**Comment by pLeBlanc93** [comment]
verified both split options work

**Comment by pLeBlanc93** [comment]
`SplitLateral` 	To split the lateral line where it intersects the point, set this value to true; otherwise, set to false.
`LateralLine_SplitMain`	To split the main line where it intersects the point, set this value true; otherwise, set to false.
