### ISSUE TITLE
Multiple Network Junction Layers

### ISSUE THREAD

**Issue by roemhildtg** [Esri/local-government-desktop-addins#140]
When I created my geometric network between storm pipes and storm structures, it also created an extra table Storm_Net_Junctions. 

![capture](https://cloud.githubusercontent.com/assets/5471079/17666278/234bc9f8-62c5-11e6-8ba5-e65762661055.PNG)

I have two fields on the storm_pipe layer F_ID and T_ID representing the from and to ids of the structures. AA is configured to update these fields using the TO_JUNCTION_FIELD and FROM_JUNCTION_FIELD rules. But it appears that AA is looking at the wrong junction table and is using `Storm_Net_Junctions` instead of my storm structures table.

```
  Setting sort order: Field - RUNORDER
  Querying table for Last Value for layer: storm_pipe
  Query Used: (TABLENAME = '*' OR TABLENAME = 'storm_pipe' OR TABLENAME like 'storm_pipe|*' OR TABLENAME like 'storm_pipe|%') AND VALUEMETHOD = 'Last_Value'
  Number of results: 0
  Querying table for rules for layer: storm_pipe
  Query Used: (TABLENAME = '*' OR TABLENAME = 'storm_pipe' OR TABLENAME like 'storm_pipe|*' OR TABLENAME like 'storm_pipe|%') AND ON_CHANGEGEO = 1
  Number of results: 4
  Looping through the rows
    ------------------------------------------------
      Row Info
        Row Number 1
        TableName: storm_pipe
        FieldName: to_struc_id
        ValueInfo: storm_struc|cid
        ValueMethod: TO_JUNCTION_FIELD
        On Create: 0
        On Change: 0

      Checking for Subtype Restriction
      Field Name: To Structure ID was found at index: 20
                  Trying: TO_JUNCTION_FIELD
                  Layer restriction found, Class name of junction is: UtilityStorm_Net_Junctions
                  Layer restriction does not match, breaking
                  Finished: TO_JUNCTION_FIELD
    ------------------------------------------------
```

Here are the configured rules:

![capture](https://cloud.githubusercontent.com/assets/5471079/17666313/519aa2b6-62c5-11e6-9c04-804fb239d71f.PNG)

**Comment by MikeMillerGIS** [comment]
You have an issue with the geometric network, I would ensure you sswr_struc is connected to the main at that location.

**Comment by roemhildtg** [comment]
You're right. Thanks. But if I run the rule on a pipe that **is** properly connected, I'm seeing this. What does "Layer restriction does not match" mean?

```
ON_CHANGEGEO = 1
  Number of results: 4
  Looping through the rows
    ------------------------------------------------
      Row Info
        Row Number 1
        TableName: storm_pipe
        FieldName: to_struc_id
        ValueInfo: storm_struc|cid
        ValueMethod: TO_JUNCTION_FIELD
        On Create: 0
        On Change: 0

      Checking for Subtype Restriction
      Field Name: To Structure ID was found at index: 20
                  Trying: TO_JUNCTION_FIELD
                  Layer restriction found, Class name of junction is: storm_struc
                  Layer restriction does not match, breaking
                  Finished: TO_JUNCTION_FIELD
    ------------------------------------------------
```

**Comment by MikeMillerGIS** [comment]
Just leave the layer restriction blank.  It limits the rule to only run on that layer.  Please review the configuration.  You have them backwards if you want to use a layer restriction
http://solutions.arcgis.com/shared/help/attribute-assistant/tools/attribute-assistant-methods/#to-junction-field

**Comment by roemhildtg** [comment]
Ah. 👍 

How did I miss that!
