### ISSUE TITLE
Autonumber fails on tables

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#141]
Reported on geonet
https://geonet.esri.com/message/631034-re-attribute-assistant-autonumber-method

**Comment by MikeMillerGIS** [comment]
resolved in https://github.com/Esri/local-government-desktop-addins/commit/9c42fa2cd8f26810ad43835f7a2a8b3809292fa9

**Comment by pLeBlanc93** [comment]
verified
