### ISSUE TITLE
Provide option in AA's config file for GenerateIDs SEQNAME and SEQCOUNTER

### ISSUE THREAD

**Issue by SASrinivas** [Esri/local-government-desktop-addins#142]
AA's config file can be updated with the name of the GenerateID table. Provide an option to use custom field names for SEQNAME and SEQCOUNTER. This helps when integrating with asset management systems.

Thanks,
Srinivas

**Comment by MikeMillerGIS** [comment]
@SASrinivas Please verify, will email compiled version

**Comment by SASrinivas** [comment]
You are awesome :-) Thanks for making the change!

**Comment by SASrinivas** [comment]
Works with custom field names in GenerateID table for SEQNAME, SEQCOUNTER and SEQINTERV.
