### ISSUE TITLE
AA: Deleting features takes a long time

### ISSUE THREAD

**Issue by roemhildtg** [Esri/local-government-desktop-addins#143]
When using a file geodatabase feature class, and AA is activated, if I select a feature and delete it, it takes an oddly long time to perform the delete. Disabling AA and the delete happens instantly. 

The feature class I'm working with happens to be in a geometric network, but I believe this occurs with any feature class.

**Comment by roemhildtg** [comment]
Update: This doesn't happen when using a sql based data source, only file gdb type.

**Comment by MikeMillerGIS** [comment]
There is a function:  public static void StopOperation(), line 823 in the AttributeAssistantEditorExtension that seems to be the culprit.  This is required so the AA will process any related records generated or updated as part of the routine.  We could expose an object to bypass this functionality to speed things up.

**Comment by MikeMillerGIS** [comment]
@vertex3

**Comment by SteveGrise** [comment]
Hmm, that's from a while ago. I suspect it takes time to listen to each
edit event and it probably takes about the same amount of time to process
even if nothing is triggered...

**Comment by MikeMillerGIS** [comment]
Added a simple bypass variable.  Speeds up batch processing, such as using the buttons.
https://github.com/Esri/local-government-desktop-addins/commit/d4eddf407ec5a68069244783d4397502507f73a6

**Comment by MikeMillerGIS** [comment]
Need to document new config tag in the AA configuration file

**Comment by pLeBlanc93** [comment]
verified bypass variable gives signification speed up

**Comment by pLeBlanc93** [comment]
## GenerateID fields

The GenerateID table must have three fields: Name, Counter, and Interval. To use fields with different names, set the SequenceName, SequenceCounter, and SequenceInterval key value to your field names. 

## Bypass edit operation

When the Attribute Assistant is enabled and features are deleted, related records are also processed by the add-in. For quicker delete operations, set the BypassEditOperationCheck key value to True.

**Comment by MikeMillerGIS** [comment]
The bypass skips processing related records

Sent from my Verizon Wireless 4G LTE DROID
On Feb 14, 2017 5:11 PM, Paul LeBlanc <notifications@github.com> wrote:
GenerateID fields

The GenerateID table must have three fields: Name, Counter, and Interval. To use fields with different names, set the SequenceName, SequenceCounter, and SequenceInterval key value to your field names.

Bypass edit operation

When the Attribute Assistant is enabled and features are deleted, related records are also processed by the add-in. For quicker delete operations, set the BypassEditOperationCheck key value to True.

-
