### ISSUE TITLE
Address tool not swapping address ranges

### ISSUE THREAD

**Issue by allisonmuise** [Esri/local-government-desktop-addins#146]
The hint text for the address tool 'Flip Roads and Swap Parity' says that it should swap the address ranges of the centerline as well as flipping the line direction. Selecting a road and then running this tool does flip the line direction but the address ranges are not changed.

I confirmed that the field names match the configuration file.

Repro on 10.4.1 and 10.5. Didn't test older versions.

**Comment by MikeMillerGIS** [comment]
@chris-fox you want to take this one?

**Comment by chris-fox** [comment]
@allisonmuise, I was debugging this on 10.4.1 and couldn't reproduce. I did see sometimes the attributes dock pane didn't refresh, but when I unselected and reselected the feature it refreshed with the correct attributes. It wasn't consistent though, sometimes it refreshed as expected. Could you see if you see the same thing? Confirm in the attribute table and attributes dock pane.

**Comment by allisonmuise** [comment]
@chris-fox : Yup I see it swapping now. It does 'stick' a bit sometimes, but eventually I see the attributes update. Weird.

I don't have a 10.5 machine to work with anymore. I can get one if you'd like me to verify there as well.

**Comment by chris-fox** [comment]
@allisonmuise, I just tested on 10.5 as well and it looks good. So I think we are good here. Thanks.

**Comment by allisonmuise** [comment]
👍
