### ISSUE TITLE
BUG-000099445  Capital Improvement Planning tools do not allow projects to be created without a point feature.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#147]
<div><div>
<span><b>Salesforce ID:</b> BUG-000099445</span><br/>
<span><b>Salesforce Submitter:</b> Andy Shoemaker</span><br/>
<span><b>Salesforce Submit Date:</b> 9/20/2016 8:58 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Equivalency</span><br/>
<span><b>Salesforce Severity:</b> High</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> 1) Create a Hydrant point in the project
2) Save the project
3) Load the project
4) Remove the Hydrant 
5) Save the Project</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.3.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Resolved issue and will make next release</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
resolved in https://github.com/Esri/local-government-desktop-addins/commit/751b992187e31b949cf36a8b618a2e74874780ed

**Comment by clareprice** [comment]
verified.
