### ISSUE TITLE
Validate Attribute Lookup Method will not allow for Nulls

### ISSUE THREAD

**Issue by mhammond0420** [Esri/local-government-desktop-addins#152]
Once a entry is made to a field with this method applied you can not empty it out. In other words once used <Null> is no longer available.

**Comment by MikeMillerGIS** [comment]
if you remove a value, it will prompt you for a valid list.  Are you looking to reset the field to Null?  You will have to toggle off the Attribute Assistant.

**Comment by mhammond0420** [comment]
That was what I was afraid of. Understand the reasoning though.

Thanks Michael.

*Melanie Hammond*
OSP Operations Support Manager | Zayo *Group*
6700 Baum Drive | Suite 9 | Knoxville, TN 37919
Desk: 303.381.3327 | Cell: 865.332.9337
*melanie.hammond@zayo.com <melanie.hammond@zayo.com>*
*Mission* <http://www.zayo.com/company/company-overview> | *Network Map
<http://www.zayo.com/network/interactive-map>** | LinkedIn
<https://www.linkedin.com/company/530962>* | *Twitter
<https://www.twitter.com/zayogroup>*

**Comment by pLeBlanc93** [comment]
verified that the cancel dialog box will null out a field with a previous value
