### ISSUE TITLE
Validate Attribute Lookup Fails when the attribute has the | as part of it

### ISSUE THREAD

**Issue by mhammond0420** [Esri/local-government-desktop-addins#153]
The table I have it referencing back to has entries such as Brazil | Hffmn_Brdg | N_CR_500E. When typing in Br and hitting enter it brings up the dropdown for me to choose and the names are listed correctly there. But when I choose something like above it abbreviates to only what is before the |. So it enters Brazil. I am aware that | is not really a good choice to have in a field but I need to know if other symbols will have the same effect.

**Comment by MikeMillerGIS** [comment]
could you send me a sample dataset?  I have a feeling there is a bug as we are probably using | internally
mmiller@esri.com

**Comment by mhammond0420** [comment]
Absolutely. I thought the | was a definite issue as I know it is how
several methods are populated.

The data is currently in a standalone table so I just exported a selection
and created a dbf. Let me know if you need anything else. Also if you paste
this email into that Issue could you please remove all of my contact info?
I noticed that was happening in the others we had worked on and removed
myself. Prefer not to have all of that sitting out there.

Thanks

*Melanie Hammond*
OSP Operations Support Manager | Zayo *Group*
6700 Baum Drive | Suite 9 | Knoxville, TN 37919
Desk: 303.381.3327 | Cell: 865.332.9337
*melanie.hammond@zayo.com <melanie.hammond@zayo.com>*
*Mission* <http://www.zayo.com/company/company-overview> | *Network Map
<http://www.zayo.com/network/interactive-map>** | LinkedIn
<https://www.linkedin.com/company/530962>* | *Twitter
<https://www.twitter.com/zayogroup>*

**Comment by MikeMillerGIS** [comment]
I you respond to the githib email. it will post that email, make sure to remove that before sending,  I will remove it from your previous reply

**Comment by MikeMillerGIS** [comment]
@mhammond0420 I think you replied to github with the attachment, this will strip the attachment, please send directly to me.

**Comment by MikeMillerGIS** [comment]
@mhammond0420 It was a bug, I resolved it and it will be included in the next release.

**Comment by SASrinivas** [comment]
Populates the value correctly. Tested with other characters such as !@#$%^&*()_+ as well.
