### ISSUE TITLE
BUG-000099828  Loading a config file in the Address Editing toolbar fails with the error message, “Error in reload Click: object reference not set to an instance of an object.”

### ISSUE THREAD

**Issue by chris-fox** [Esri/local-government-desktop-addins#155]
<div><div>
<span><b>Salesforce ID:</b> BUG-000099828</span><br/>
<span><b>Salesforce Submitter:</b> Jacob Lias</span><br/>
<span><b>Salesforce Submit Date:</b> 10/05/2016 7:33 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by chris-fox** [comment]
The reload functionality is not longer needed for the address data management and other add-in config files. It is only required for Attribute Assistant. Since they use different dialogs this fix just removed the reload button.

**Comment by pLeBlanc93** [comment]
verified no more reload
