### ISSUE TITLE
BUG-000100426  The ArcGIS Solutions documentation for Configure the Water Utility Editing tools incorrectly states that the configuration file can be accessed from the add-in's toolbar.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#157]
<div><div>
<span><b>Salesforce ID:</b> BUG-000100426</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 10/28/2016 5:40 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Documentation</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000100426</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Electric, Gas, Water and Telecommunications</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Issue has been resolved and the button will be shown with the next release of the add in, currently planned for Feb.</span><br/>
</div></div>

**Comment by clareprice** [comment]
Related to #158
