### ISSUE TITLE
ENH-000100427  Add a Show Config Information (Water) (Button) with the Water Utility Network Editing and Analysis solution.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#158]
<div><div>
<span><b>Salesforce ID:</b> ENH-000100427</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 10/28/2016 5:49 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\ENH-000100427</span><br/>
<span><b>Work Around:</b> 1. Provide the appropriate/comparable step by step workflow to help illustrate the request.<br>See the attached document with an explanation and screenshots.<br>The Gas Utility Network Tools as well as Attribute Assistant have buttons that are either on the toolbar by default (AA) or can be added to the toolbar (Gas).<br>But there is no such button for the Water Utility Network Editing and Analysis solution.<br> <br>2. What is the problem feature X is trying to solve? (i.e. What is the problem/limitation/design choice that is preventing the customer from moving forward?)<br>The Show Config Information button makes these solutions far easier to use, especially for customers who manage multiple configuration files that are specific to different jobs.<br><br>3. What are the benefits or changes that would result from the enhancement? (i.e. How does making this change help the customer&#39;s workflow or business?)<br>The Water solution would be easier to use for customer who manage different config files.</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Electric, Gas, Water and Telecommunications</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Will be included in the next release, currently planned for Feb.</span><br/>
</div></div>

**Comment by clareprice** [comment]
@MikeMillerGIS Verified the Show Config Information (Water) is on toolbar.
