### ISSUE TITLE
BUG-000100417  In the Attribute Assistant Config and Log File Dialog box, the Configuration Files section should not list the all files contained in subfolders of the ..\ArcGISSolutions\ConfigFiles folder, if they cannot be loaded to be used as the Loaded.config file.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#159]
<div><div>
<span><b>Salesforce ID:</b> BUG-000100417</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 10/27/2016 2:19 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000100417</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Config files in folder will be loaded, resolved the bug.  New option added to the dialog to not back up the existing config file.  This will support the placing files in folder better.</span><br/>
</div></div>

**Comment by SASrinivas** [comment]
The Config and Log File Dialog does not list any of the Configuration Files in ConfigFiles folder.

**Comment by pLeBlanc93** [comment]
related to #180 ?

**Comment by MikeMillerGIS** [comment]
They only list the valid files for the tool, so for the AA, it would be blah.aa.loaded.  can you post a screen shot of what you are experiencing?

**Comment by MikeMillerGIS** [comment]
Here is what I am seeing

![image](https://cloud.githubusercontent.com/assets/2707285/22936272/f6a575e8-f2a2-11e6-8285-f40411de62de.png)

![image](https://cloud.githubusercontent.com/assets/2707285/22936280/0058c978-f2a3-11e6-9046-138a1f2a5d95.png)

![image](https://cloud.githubusercontent.com/assets/2707285/22936288/0aa45352-f2a3-11e6-8f1f-4ad98ea6ae27.png)

![image](https://cloud.githubusercontent.com/assets/2707285/22936301/1574cda2-f2a3-11e6-9b34-5764f6fd7ac1.png)

**Comment by SASrinivas** [comment]
I am not seeing any config files in the list. The configuration in loaded.aa.config is different from WMWD_AA.config, but WMWD_AA.config is not listed. Samething with loaded.water.config and WMWD_water.config

Do we need two sections in the dialog, one each for AA config and the solution config (water, gas etc.)?
![config files](https://cloud.githubusercontent.com/assets/9484194/22937448/8051b1aa-f28d-11e6-8c2b-7b6d02b1bb92.jpg)

**Comment by MikeMillerGIS** [comment]
Do they have the same name in the file?

**Comment by SASrinivas** [comment]
No
loaded.aa.config has Attribute Assistant Release
WMWD_AA.config has WMWD Attribute Assistant
loaded.water.config has Water Release
WMWD_water.config has WMWD

**Comment by MikeMillerGIS** [comment]
the file names are incorrect.  it is name.app.config.  you only have name.config.  change the _ to a .

**Comment by SASrinivas** [comment]
Renaming worked. I can see the multiple aa config files now :-)

**Comment by pLeBlanc93** [comment]
> the file names are incorrect. it is name.app.config. you only have name.config. change the _ to a .

Will document the naming conventions.
