### ISSUE TITLE
BUG-000100776  Attribute Assistant tool trims double value to 2 decimals when "," is used as separator

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#163]
<div><div>
<span><b>Salesforce ID:</b> BUG-000100776</span><br/>
<span><b>Salesforce Submitter:</b> Eiswary Nadarajoo</span><br/>
<span><b>Salesforce Submit Date:</b> 11/14/2016 10:15 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Data</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000100776</span><br/>
<span><b>Work Around:</b> Go to Control Panel > Region > Additional Settings > Decimal Symbol. Change the value from comma (,) to point (.)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
linking issues
https://github.com/Esri/local-government-desktop-addins/issues/160

**Comment by tiagorodriguesribeiro** [comment]
Hello Mike.

Nice to ear that this issue have been fixed. Since I've been the one that detected this issue and we need to put this working on a client can you tell me (if you know...) when it's going to be the "Next Release"?

Best regards,
Tiago Ribeiro.

**Comment by MikeMillerGIS** [comment]
Plan is February.

**Comment by shoe913** [comment]
Tested with comma localization, the Bug appears resolved and the tool is working as expected.
