### ISSUE TITLE
BUG-000100689  In the Capital Improvement Planning Solution, Date Completed is still populated in the CIP feature classes even when the check box is left unchecked for the Date Completed attribute in the CIP Project Details of the Project Cost Estimating Window.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#167]
<div><div>
<span><b>Salesforce ID:</b> BUG-000100689</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 11/09/2016 9:38 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> (n/a)</span><br/>
<span><b>Functional Category:</b> ArcGIS for Electric, Gas, Water and Telecommunications</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> (n/a)</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by clareprice** [comment]
@MikeMillerGIS Verified.
