### ISSUE TITLE
Junction rotate fails on non Geometric network features

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#170]
If the last parameter is omitted, it fails to find a matching angle

Workaround: specify the layers in the last parameter

ex: g|0||Pipes

**Comment by SASrinivas** [comment]
Works when a non-geometric network or geometric network point is connected to a geometric network line.
Does not work when a non-geometric network or geometric network point is connected to a non-geometric network line.

**Comment by MikeMillerGIS** [comment]
A geometric network feature will only work when intersecting a geometric network feature.  A non network feature should work with anything.  I can test that.

Should we allow a network feature to work with non network features?

**Comment by MikeMillerGIS** [comment]
@SASrinivas I tested a non geo point and it is getting an angle regardless of if the intersecting line is in the GN or not.
