### ISSUE TITLE
BUG-000101534  In an ArcMap session, after running the first feature abandon operation with the Abandon Water Assets tool from the Water Utility Network Editing and Analysis toolbox, subsequent attempts to abandon more features always fail with the following runtime error, "The requested operation is invalid on a closed state."

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#171]
<div><div>
<span><b>Salesforce ID:</b> BUG-000101534</span><br/>
<span><b>Salesforce Submitter:</b> Liting Cui</span><br/>
<span><b>Salesforce Submit Date:</b> 12/15/2016 4:46 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS GIS Server</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by clareprice** [comment]
THis issue has been resolved with the June 27th release of ArcGIS Solutions.
