### ISSUE TITLE
BUG-000100965  The Split Intersecting Feature method in the Attribute Assistant add-in does not properly split lines.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#173]
<div><div>
<span><b>Salesforce ID:</b> BUG-000100965</span><br/>
<span><b>Salesforce Submitter:</b> Rachel Applebaum</span><br/>
<span><b>Salesforce Submit Date:</b> 11/22/2016 3:48 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Performance</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000100965</span><br/>
<span><b>Work Around:</b> Use the Split Line at Point tool. For more information on the tool, refer to http://arcg.is/2f4p3m3.</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> The cursor used in the split was recycled, causing the operation fail</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
A recycled curors was used, switched to a non recycling cursor resolved the issue.

**Comment by shoe913** [comment]
Tested issue with sample data supplied for bug. 

Everything appears to be working as expected, thanks!
