### ISSUE TITLE
BUG-000101998  The Attribute Assistant method, 'onChange (attribute)' is triggered when connections are made in a geometric network.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#177]
<div><div>
<span><b>Salesforce ID:</b> BUG-000101998</span><br/>
<span><b>Salesforce Submitter:</b> Andy Shoemaker</span><br/>
<span><b>Salesforce Submit Date:</b> 1/09/2017 4:52 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000101998</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.2.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Was able to repo and will change event to  geometry change event as this is closer to the events we monitor than an attribute change event.</span><br/>
</div></div>

**Comment by shoe913** [comment]
Tested behavior workflow against data logged with bug, everything works as expected. 

Thanks!

**Comment by SASrinivas** [comment]
It works as expected. When connections are made, the geometric network is updated, which triggers the ON_CHANGEGEO rules.
