### ISSUE TITLE
New Rule - Validate Domains

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#179]
When a field is changed, validate its attribute values to ensure they are valid if the field has a range or coded value domain.

**Comment by MikeMillerGIS** [comment]
Description: This rule validates data entry on fields with domains against the domain.  If the value falls outside the range or not in the coded value list, the edit is aborted.

VALUEMETHOD: VALIDATE_DOMAIN
FIELDNAME: Field1, Field2, ...
VALUEINFO: Nothing

Note:  This rule is not valid for On_Manual

**Comment by MikeMillerGIS** [comment]
checked in - https://github.com/Esri/local-government-desktop-addins/commit/cfe662f2401663240794957c3c85451283ba945f

**Comment by guruesri** [comment]
Hi Mike,

Let us run 'Sort Domain' GP tool on the VALUEMETHOD domain. This will help show the value methods in ascending order when the user uses this table during configuration.

Thanks,
Guru

**Comment by MikeMillerGIS** [comment]
@guruesri ty, updated our master repo with the datasets to have a sorted domain

**Comment by SASrinivas** [comment]
When I populate a field with a value that is not part of the domain, I get the Field Calculator warning. When I click Yes on that dialog, the incorrect value gets populated.
![validate domain](https://cloud.githubusercontent.com/assets/9484194/22897217/cd307bf2-f1d7-11e6-9952-f5a426b06073.png)

**Comment by MikeMillerGIS** [comment]
Why would you click yes :)  What value is being populated?

**Comment by SASrinivas** [comment]
:) out of curiosity. In the wFitting feature class, I input Testing for FITTINGTYPE and it took it.

**Comment by MikeMillerGIS** [comment]
I am not sure we can do much here, we are aborting the operations for each edit, somehow the field calculator is still setting the values.

**Comment by MikeMillerGIS** [comment]
I will move to a known issue

**Comment by SASrinivas** [comment]
Maybe we mention it in the doc to click No in the Field Calculator warning?? This way users know that clicking Yes will populate values outside of the Domain.

**Comment by MikeMillerGIS** [comment]
@pLeBlanc93 lets include this in the doc - https://github.com/Esri/local-government-desktop-addins/issues/190

**Comment by pLeBlanc93** [comment]
new method documented and caution note added about `yes`
