### ISSUE TITLE
Expose option to set split type

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#181]
Expose option to control how the split is performed.  By default, the split first trys to split a feature by shorting the existing segment and add a new feature for the shorter piece and if fails, does the following.

Setting the following tag to true, which is the default in the config file, will attempt the split and update,
Setting the follwong tag to false deletes the existing feature and adds two new features.  

Note: Make sure to turn off Suspend AA on Split if you want to fire the AA on the new/changed features
```

<MergeSplitGeoNetFeatures>
    <!--Option to control how the split is performed.  True trys to split a feature by shorting the existing segment
      and add a new feature for the shorter piece.  False deletes the existing feature and adds two new features.  Make sure to 
      turn off Suspend AA on Split if you want to fire the AA on the new/changed features
    -->
    <SplitUpdateAndAdd>true</SplitUpdateAndAdd>
```

**Comment by MikeMillerGIS** [comment]
Option to control how the split is performed when using the Add Point and Split Intersecting Line construction tool or the Split Line at Points tool on the Water/Gas Editing Toolbar.  True first attempts to reshape the existing feature and add a new one.  There are scenarios where this is not valid and it falls back on a delete and two adds.  Specifing False performs the delete and adds first. 

You can use this in conjunctions with the Generate ID AA rule.  

Scenario 1:  When I split a feature, I want two new IDs
  The value method for the Generate ID should only be set to On_Create.  The value info will look like this, WATERMAIN|0|[seq]-main|False.  The key is the last option to not preserve the ID as a split operations copies the existing features information to the new features.  You will want to use
 <SplitUpdateAndAdd>false</SplitUpdateAndAdd>


Scenario 2:  When I split a feature, I want to maintain the existing IDs, but want two new records
  The value method for the Generate ID should only be set to On_Create.  The value info will look like this, WATERMAIN|0|[seq]-main|True.  The key is the last option to not preserve the ID as a split operations copies the existing features information to the new features. 
 <SplitUpdateAndAdd>false</SplitUpdateAndAdd>

**Comment by pLeBlanc93** [comment]
added a workflow page to AA explaining the 4 scenarios.
