### ISSUE TITLE
Prompt dialog not properly sized

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#183]
If label is larger than the largest value, dialog not resized appropriately

**Comment by MikeMillerGIS** [comment]
![image](https://cloud.githubusercontent.com/assets/2707285/22887056/9baef0a8-f1ce-11e6-8361-2db29a1dc3d1.png)

**Comment by MikeMillerGIS** [comment]
https://github.com/Esri/local-government-desktop-addins/commit/cb359162310d1640c682663d0f792f08d06b12af

**Comment by MikeMillerGIS** [comment]
@pLeBlanc93 @clareprice FYI

**Comment by SASrinivas** [comment]
Tested on a few feature classes and fields. Dialog box looks good.

Srinivas
