### ISSUE TITLE
Crash - when running a rule manually on a Parcel Fabric dataset

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/local-government-desktop-addins#184]
![nullreference](https://cloud.githubusercontent.com/assets/5614261/22894923/8c07a810-f1cf-11e6-9700-92eaa8025fff.PNG)

Dynamic values and generateid tables attached

[DynamicValuesGenerateid.gdb.zip](https://github.com/Esri/local-government-desktop-addins/files/771883/DynamicValuesGenerateid.gdb.zip)

**Comment by ChrisBuscaglia** [comment]
@clareprice This happens because the ParcelFabric|Lots and Units should be  **ParcelFabric_Parcels|Lots and Units**  Incorrect in the DV table - but probably shouldn't crash.

**Comment by MikeMillerGIS** [comment]
unable to repo
