### ISSUE TITLE
When toggling Attribute Assistant on without a dynamic value table added to map, provide an error

### ISSUE THREAD

**Issue by jaso2k** [Esri/local-government-desktop-addins#185]
I was attempting to toggle Attribute Assistant on but realized I didn't have the dynamic value table in the map.  There should be an error message or some sort of information provided to the user why they are unable to toggle Attribute Assistant on.

**Comment by pLeBlanc93** [comment]
We mention it in the FAQ http://solutions.arcgis.com/shared/help/attribute-assistant/get-started/faq/#turn-on

could also present a dialog box

**Comment by pLeBlanc93** [comment]
verified dialog box
