### ISSUE TITLE
Show/Hide Flow Direction

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#19]
Using 10.3, the flow direction symbols remain displayed despite layer being turned off in the table of contents. This behavior had not occurred in 10.2.2. Steps to repo: 
1. Turn on sewer network, and select the show/hide flow direction tool
2. Uncheck the group layer in the table of contents. Flow direction will persist. 
3. Try to hide flow direction, flow direction arrows will remain.
4. Turn group layer back on and turn off flow direction. Arrows will be hidden.
![image](https://cloud.githubusercontent.com/assets/5611508/4387478/30a02ba2-43dd-11e4-8bc9-a5617d294f43.png)

**Comment by MikeMillerGIS** [comment]
Known Issue, closing
