### ISSUE TITLE
Is the field name case sensitive

### ISSUE THREAD

**Issue by barmaor** [Esri/local-government-desktop-addins#196]
It is not clear if the field name should be:

- upper case
- lower case
- mixed case

it is not mentioned in the doc
not clear if this would have an impact on DBMS

**Comment by MikeMillerGIS** [comment]
Field name needs to match the gdb field name.  As for case, let me double check

**Comment by MikeMillerGIS** [comment]
Case sensitive

Using the fields findfield method

https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Esri_local-2Dgovernment-2Ddesktop-2Daddins_blob_dev_ArcGISTemplateSharedFunctions_Globals.cs-23L16623&d=DwIGaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=g9GbJBW7AIf3hxxb8BMwFB8HhrwoElkbhRnTZajhloekQxG14tIQdwlcYQvSIebPdIn0Lns9xWarXf_TTNoZxH2DB0jiZLKWdGOiH00_0MuGnssg8GW5V1IotjJZKzi2mcM6wrw0dTNghY7TysMEhg&m=8lbOU15l_fPxthvzQ9R2iUZRtppVXrJQdjk5gn7Y8QE&s=HTiCEVQ6NCkIF3HceyZsxKO17iH1feKwb7xtFE7uap4&e= 

Sent from my Verizon Wireless 4G LTE DROID

**Comment by pLeBlanc93** [comment]
Field names are **not** case sensitive -- just verified on FGDB and EGDB (sql server)

I'll make a note in the documentation

**Comment by pLeBlanc93** [comment]
## FIELDNAME
This field defines the field upon which the Attribute Assistant actions will be applied or the field to monitor for changes. The values need to be the field name (case insensitive) of the table, not the alias.
