### ISSUE TITLE
CRASH: When creating a Parcel a locking error is presented and software might hang/crash

### ISSUE THREAD

**Issue by jaso2k** [Esri/local-government-desktop-addins#199]
Install Attribute Assistant
Open the attached MXD

[1PublicLandSurveyEditing - MT on GPS SDE.zip](https://github.com/Esri/local-government-desktop-addins/files/772557/1PublicLandSurveyEditing.-.MT.on.GPS.SDE.zip)

Start Editing (note: Edting on DEFAULT and Dynamic Values table is in the map)
Add the Parcel Editor (PE) Toolbar to the map
Click on NEW PARCEL, 2nd button on the PE toolbar
Click in the map and digitize a square parcel (you might need to right click in the map and make sure Digitize is turned on by clicking it in the context menu)
In the Parcel Details window click KEEP AND JOIN, 4th button from the left in the window.
In the JOIN dialog click OK
At this point you will get a locking message that only occurs when Attribute Assistant is installed
![lockingimage](https://cloud.githubusercontent.com/assets/15934155/22906263/95813a0e-f1f8-11e6-91a8-8fb9a4bda81e.PNG)
Click ok on the error and this is where the software might hang/crash
I've attached the crash dump generated from the times I've gotten it to crash
[CrashDump.zip](https://github.com/Esri/local-government-desktop-addins/files/772592/CrashDump.zip)

**Comment by clareprice** [comment]
https://esri.app.box.com/files/0/f/19029615810/Crash_Dump

**Comment by jaso2k** [comment]
I uploaded a more verbose crash dump to the above location.  It's about 1GB in size.

**Comment by jaso2k** [comment]
Upon analysis of another crash dump I've generated on my machine it seems to be something with cadastralUI.dll

**Comment by ChrisBuscaglia** [comment]
CR340544 @jaso2k @tekwen
