### ISSUE TITLE
Connect Closest does not process all the points

### ISSUE THREAD

**Issue by SASrinivas** [Esri/local-government-desktop-addins#200]
When multiple points are selected and some of them are not processed even though they are within the search threshold in the config file. It appears that when it encounters a point that cannot find another point within the threshold, it stops processing further.
![connectclosest](https://cloud.githubusercontent.com/assets/9484194/22906965/ce0dc894-f1fb-11e6-8aa7-c66a5a5887ca.png)

**Comment by MikeMillerGIS** [comment]
Thanks, found the issue
