### ISSUE TITLE
Ability to filter intersect count

### ISSUE THREAD

**Issue by roemhildtg** [Esri/local-government-desktop-addins#218]
Use case:

I have a parking lot polygon layer, and a parking space point layer. I'd like to popuplate two fields.

 - One is a count of intersecting parking spaces where Type = 'Handicapped'
 - The other is a total count of intersecting parking spaces

Is this already possible?

**Comment by MikeMillerGIS** [comment]
Intersect stats can get you the second one and the first.  I believe if you create a layer with only handicap spots, the intersect stats will honor that.

**Comment by roemhildtg** [comment]
Wow, that is fantastic! Thanks @MikeMillerGIS you guys are awesome, attributes assistant keeps getting better.

**Comment by roemhildtg** [comment]
Looking into this again, I'm first just trying to get a total count of spaces using the Intersecting Count value method. 

 - poi_ring_buffer is a simple polygon layer, the table name is the same as the feature class name. 
 - total_space is a short integer type field on that table. 
 - Parking Space is the name of my point features that I would like to get a total count for

This is throwing an error though...am I missing something obvious (again)?

  Setting sort order: Field - RUNORDER
  Querying table for Last Value for layer: poi_ring_buffer
  Query Used: (TABLENAME = '*' OR TABLENAME = 'poi_ring_buffer' OR TABLENAME like 'poi_ring_buffer|*' OR TABLENAME like 'poi_ring_buffer|%') AND VALUEMETHOD = 'Last_Value'
  Number of results: 0
  Querying table for rules for layer: poi_ring_buffer
  Query Used: (TABLENAME = '*' OR TABLENAME = 'poi_ring_buffer' OR TABLENAME like 'poi_ring_buffer|*' OR TABLENAME like 'poi_ring_buffer|%') AND ON_CREATE = 1
  Number of results: 1
  Looping through the rows
    ------------------------------------------------
      Row Info
        Row Number 1
        TableName: poi_ring_buffer
        FieldName: total_space
        ValueInfo: street_parking_space
        ValueMethod: INTERSECTING_COUNT
        On Create: 1
        On Change: 1

      Checking for Subtype Restriction
      Field Name: total_space was found at index: 9
ERROR: INTERSECTING_COUNT for layer poi_ring_buffer is not a valid method, check the dynamic value table
    ------------------------------------------------
DONE
---------------------------------------

**Comment by roemhildtg** [comment]
Okay, it was something obvious, the value method is called `INTERSECT_COUNT` but the geodatabase domain that comes with AA is listed as `INTERSECTING_COUNT`

![image](https://cloud.githubusercontent.com/assets/5471079/25280536/eb252424-266f-11e7-9b82-f289e4a5558b.png)
