### ISSUE TITLE
Attribute Assistant - Expression - Expose option to get last value of field

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#219]
The ability in an expression to access the last value of a field that changed.  
To do this, we expose a new way to get the previous value of a field.  You will use the [FieldName] format, but a ~ will be added in front of the field name, like below:
[~fieldname]

Note:  
  - A row is not changes, the fields value will be used
  - Previous values are not check on the create of a feature as this would override and revert the feature templates values.

This will look at the year entered, if that year is greater that the current year, reset the edit to the previous value.
Example:  IIF([YEAR] > CInt(Year(Now())),[~YEAR],[YEAR])

**Comment by clareprice** [comment]
Verified. Closing.
