### ISSUE TITLE
Attribute Assistant + Split Line at Point construction tool error

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#220]
When using a AA rule that will abort the edit operation, the split line at point tool can raise an error when calling IFeature.store.  I cannot monitor the Edit Event and look for an aborted edit operation as this is being fired about the error is being reported on IFeature.Store.  I can use a try catch to capture the error on store and present a message like this:

![image](https://cloud.githubusercontent.com/assets/2707285/24103184/d8457a4a-0d54-11e7-9346-34843e1ab613.png)

**Comment by clareprice** [comment]
@MikeMillerGIS For testing and verification, what are a few examples of AA methods/rules that would end the edit operation?

**Comment by MikeMillerGIS** [comment]
What about minimun length, such as trying to split a main and creating a small segment

**Comment by previnWong** [comment]
Would/should the following workflow cause AA to abort an edit?  I set the Value Info to a field that does not exist.

1) Open AA dynamic value table, change the rule for Control Valve
2) set the rule Intersect_Feature, the value info to DIAMETER99 to ensure on a valid rule
3) Place on Control Valve on a Main
4) in Water Editing Toolbar, click the tool Split line at selected points
5) No error message is displayed.  Diameter field in Control valve remains null

**Comment by MikeMillerGIS** [comment]
Should just add an entry to the log file, does not abort edit.

Sent from my Verizon 4G LTE Droid

**Comment by clareprice** [comment]
Verified. Closing.
