### ISSUE TITLE
ENH-000103893  Ignore custom fields added to the CIP Project Outlines Feature when a project is modified and subsequently overridden.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#223]
<div><div>
<span><b>Salesforce ID:</b> ENH-000103893</span><br/>
<span><b>Salesforce Submitter:</b> Andy Shoemaker</span><br/>
<span><b>Salesforce Submit Date:</b> 3/22/2017 4:40 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Low</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> 1. Provide the appropriate/comparable step by step workflow to help illustrate the request.<br><br>When working the with Capital Improvement Plan Project Cost Estimating tools, users will often times add their own fields to the Project Outlines Feature. This allows them to track projects with IDs other than those created automatically by the system and have more granular control over what projects are connected outside of their database. When such a field is being used, the project can be loaded into the project cost estimating window to be modified. When this project is saved via &quot;Save Selected Assets to a Project&quot;, the custom fields are cleared out.<br><br>2. What is the problem feature X is trying to solve? (i.e. What is the problem/limitation/design choice that is preventing the customer from moving forward?)<br><br>Important data is being removed from customized CIP Projects layers when a project is overwritten. Since these tables and tools are marketed as customizable, clearing data that appears in custom fields defeats the purpose of modifying feature classes and using the solutions.<br><br>3. What are the benefits or changes that would result from the enhancement? (i.e. How does making this change help the customer&#39;s workflow or business?)<br><br>Allowing the tool to either ignore custom fields or creating a functionality for users to easily add their own fields to the Details tab of a project so data is not lost. Ultimately this gives the user more control and flexibility with their data both within and outside of our products</span><br/>
<span><b>Product:</b> (n/a)</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> (n/a)</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Will evaluate and look at a fix for the next release</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
closed on the backend to match support app
