### ISSUE TITLE
BUG-000103189  Attribute Assistant Copy Linked Record method, fails to run when making a geometry change on a polygon that participates in a relationship class.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#224]
<div><div>
<span><b>Salesforce ID:</b> BUG-000103189</span><br/>
<span><b>Salesforce Submitter:</b> Alex Gil</span><br/>
<span><b>Salesforce Submit Date:</b> 2/24/2017 4:16 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000103189</span><br/>
<span><b>Work Around:</b> 1.	After splitting circle using the cut polygon tool, manually run the ‘Run Manual Rules for Selected Features’ from the Attribute Assistant toolbar.
2.	Remove the relationship between feature class “Parcel_AA” and table “Parcel_Info.</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.3.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Will evaluate and look into resolving for the next release</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
Traced this down, it is not something we can fix in the AA.  Attached is code to repo this outside the AA.  
[BugRepo.zip](https://github.com/Esri/local-government-desktop-addins/files/1556401/BugRepo.zip)


- Polygon layer is related to table through a field called PIN(on both classes)
- In the code, I am creating a IQueryFilter to query the table
- The where clause is PIN = 1.  The PIN field is the foreign key in the relationship
- This always returns 0
- If I use 1=1, all the records are returned.  If I use another field, not the PIN field, I get the appropriate records.
- IQueryFilter past to ITable.Search or ITable.RowCount is failing to return records when the field being queried is foreign key in a relationship
- This only occuers with the split on the editor toolbar
- Does not occur when using IFeatureEdit.split

**Comment by LindsayThomas** [comment]
Closing to match backend support app
