### ISSUE TITLE
Enhancements to INTERSECT_STATS

### ISSUE THREAD

**Issue by SASrinivas** [Esri/local-government-desktop-addins#23]
1) The INTERSECT_STATS uses comma when concatenating the values extracted from multiple features. Ability to change this to use a delimiter of users choice such as / or - etc. would be helpful.

2) Provide the ability to sort the values being stored either ascending or descending.

**Comment by MikeMillerGIS** [comment]
New parameters added to the following methods:
INTERSECT_STATS (5th and 6th parameter)
FEATURE_STATS  (3rd and 4th parameter)
TO_EDGE_STATS (3rd and 4th parameter)
FROM_EDGE_STATS (3rd and 4th parameter)
EDGE_STATS (3rd and 4th parameter)

First parameter added is the delimiting character, you cannot |
Second parameter added is the sort order asc or desc is supported.

Example for INTERSECT_STATS 
wMain|DIAMETER|Concat|15|;|ASC

**Comment by MikeMillerGIS** [comment]
Help updated
