### ISSUE TITLE
Intersecting_feature - Search tolerance rework

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#236]
The code was using the map tolerance which can change depending on the view scale.  Switched to use 10* the xytolerance of the data or map, what ever is larger.
<span><b>Salesforce ID:</b> BUG-000107033</span><br/>

**Comment by clareprice** [comment]
@MikeMillerGIS Reviewing the data attached to this bug, is the expected behavior that a dialog to select the options would be presented at all map scales?

https://qamonitor/SFTriage?sfid=BUG-000107033

**Comment by MikeMillerGIS** [comment]
The issue was depending on scale, the intersect would get a different set of features as the search extent grow.  I was based on map scale.  So I changed it to be based on the tolerance of the data.  So zoomed in or out, the same set of intersecting candidates are found
