### ISSUE TITLE
BUG-000104801  Attribute Assistant Value Method Field_Trigger is not working for manual or geometry changes.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#238]
<div><div>
<span><b>Salesforce ID:</b> BUG-000104801</span><br/>
<span><b>Salesforce Submitter:</b> Barbara Sieg</span><br/>
<span><b>Salesforce Submit Date:</b> 4/28/2017 8:30 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000104801</span><br/>
<span><b>Work Around:</b> Use the Expression value method instead. Set the FieldName to the field to be updated, not the field to monitor. The ValueInfo can be similar to this:
IIF ([<field to monitor>] = <trigger value>, <target value>, [<field to be updated>])</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.5</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> The current code for field trigger will only run if the field is changed.  We can bypass this check so the rule runs for On Manual as well as the other rules.</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
* Field trigger can we triggered from the toolbar tools regardless if the field has changed.

**Comment by previnWong** [comment]
@MikeMillerGIS can you check this scenario.  doesn't work in 10.6 or 10.2

Start an edit session and enter "Drunkenness" in the Problem field.
In the Dynamic Value table, change On_Manual to 0 and On_ChangeGeo to 1.
Select the first feature in Incidents and move the feature. The Problem2 field is not updated. **(not working)**
Click the "Run Change Geometry Rules" button; nothing happens.  **(works)**

**Comment by MikeMillerGIS** [comment]
yes, it probably should.  What the code is doing is checking if the row changed to process the rule.  It bypasses this check if you click any of the tools on the AA, it is not checking if you did actually changed the geo.  I can make that fix, but not worth a rebuild,

**Comment by MikeMillerGIS** [comment]
I think we should move this back to in Dev and pick up next time

**Comment by MikeMillerGIS** [comment]
@previnWong @clareprice based on previns findings, moving out of installed and setting to the next deliverable.

**Comment by MikeMillerGIS** [comment]
fix:
 if (pRowCh.get_ValueChanged(intFldIdxs[0]) == true || mode == "ON_MANUAL" ||
                                                        AAState.triggerByTools == AAState.TriggerByToolsOptions.Manual ||
                                                        AAState.triggerByTools == AAState.TriggerByToolsOptions.Geo ||
                                                        AAState.triggerByTools == AAState.TriggerByToolsOptions.Change ||
                                                        AAState.triggerByTools == AAState.TriggerByToolsOptions.Create)
                                                    {

Add checking for On_Change_Geo to this block

**Comment by LindsayThomas** [comment]
Closing to match backend support app
