### ISSUE TITLE
BUG-000105799  Pressurized Mains Cannot be used in the Water Utility Network Profiling tool

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#249]
<div><div>
<span><b>Salesforce ID:</b> BUG-000105799</span><br/>
<span><b>Salesforce Submitter:</b> Andy Shoemaker</span><br/>
<span><b>Salesforce Submit Date:</b> 6/13/2017 12:42 PM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
This is closed in Triage. closing to match.
