### ISSUE TITLE
Enhancement - Call On Create for a feature which was split

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#251]
Request was to trigger the on create event and not the On Change Geo event when a feature is split.  A split can trigger a change and add event, in this case, it will trigger a add and add event.

**Comment by MikeMillerGIS** [comment]
New option added to the loaded.aa.config

```
<!--Option to call on create in addition to on geo change when a line or polygon is split using the Split Tool.-->
    <add key="OnCreateWhenSplit" value="False"/>
```

**Comment by SteveGrise** [comment]
Looks great Mike. Was looking at effort to distribute with config changes, would it be possible to set this in GenerateID value info as well? 

![image](https://user-images.githubusercontent.com/4749060/27343537-3e3a5f06-55b1-11e7-9679-9e99d4ba2299.png)

The behavior here is essentially the Keep Existing flag - I even tried this hoping it would do what I wanted - replace the existing ID on a split/cut.
