### ISSUE TITLE
BUG-000106328  The Merge Network Lines tool in the Water Utility Network Editing toolbar fails and generate system errors if a subtype is set on a line feature.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#253]
<div><div>
<span><b>Salesforce ID:</b> BUG-000106328</span><br/>
<span><b>Salesforce Submitter:</b> Andy Shoemaker</span><br/>
<span><b>Salesforce Submit Date:</b> 7/05/2017 1:58 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Usability</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Traced the issue to trying to set the subtype to a value from a feature that is not a valid subtype.</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
If the feature selected has an invalid subtype, then the default subtype code is used to merge the features.

**Comment by pLeBlanc93** [comment]
@MikeMillerGIS the fix looks good.
