### ISSUE TITLE
Intersecting Feature - Support Last - The highest OID returned in set of features

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#254]
Request from NIW.  Want the highest OID feature.

Request is for when only one layer is set in value info.

**Comment by MikeMillerGIS** [comment]
Added support for H or HIGHEST in intersecting feauture

 ssPressurizedMain,ssGravityMain|DIAM|H|True

this will use the main with the highest OID.

H = Use the feature with the highest Object ID of the intersecting feature

**Comment by clareprice** [comment]
Verified doc and fix. Closing.
