### ISSUE TITLE
Previous Valve is storing the object after the change, which commits the change

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#260]
This results in IRowChange not detecting the field it is settting.  We need to move all inObject and inFeature store operations to after all rules have been processed.  This will allow any feature that used IRowChange to work

Issue reported on https://geonet.esri.com/message/716960-re-attribute-assistant-rules-issues-previous-value-and-intersect?commentID=716960
<span><b>Salesforce ID:</b> BUG-000108504</span><br/>

**Comment by AhmedTambe** [comment]
The issue still persists with Attribute Assistant version 2017.3.1, while working with ArcGIS Desktop 10.5. Could you please confirm which version of attribute assistant the behavior is fixed.

**Comment by MikeMillerGIS** [comment]
It is not fixed, only logged the issue.  Issue is open still

**Comment by AhmedTambe** [comment]
Thank you for your response Mike. Currently is there any workaround for the issue ?

**Comment by MikeMillerGIS** [comment]
I do not think there is

**Comment by AhmedTambe** [comment]
ok, Thank you for the prompt response.

**Comment by MikeMillerGIS** [comment]
Verified in dev branch

**Comment by MikeMillerGIS** [comment]
@AhmedTambe this has been implemented in the preview builds
https://github.com/Esri/local-government-desktop-addins/tree/dev/PreviewBuilds

**Comment by AhmedTambe** [comment]
@MikeMillerGIS : Thank you Mike. Just tested it. Works Perfect!!
