### ISSUE TITLE
Documentation Change Request

### ISSUE THREAD

**Issue by tforward** [Esri/local-government-desktop-addins#262]
In the Function Notes for the Expression Rule it says:

```
To set values as null, use an empty string:
Invalid: IIF([LOCDESC]=0, "", [LOCDESC])
Valid: IIF([LOCDESC]=0, "<NULL>", [LOCDESC])
```

Can it be changed to read : 

`To set values as null, use "<NULL>" string:`

as when read empty string "" would apply

**Comment by MikeMillerGIS** [comment]
can you make this doc change?

**Comment by tforward** [comment]
Right

**Comment by MikeMillerGIS** [comment]
sorry, I forgot to @clareprice @Elena9170 can you make the doc changes.  that was not directed at @tforward sorry for the confusion.

**Comment by tforward** [comment]
How long does a doc change typically take?

**Comment by MikeMillerGIS** [comment]
Sorry, we missed this one in the last release.  I will tag it so we can get it fixed in the next

**Comment by MikeMillerGIS** [comment]
I checked with the doc team, the fix is out:
http://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#expression
