### ISSUE TITLE
BUG-000108521  Results from upstream and downstream trace via the Water Utility Network Reporting toolbar do not appear in the Editor Attributes window during an edit session.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#263]
<div><div>
<span><b>Salesforce ID:</b> BUG-000108521</span><br/>
<span><b>Salesforce Submitter:</b> Anna Hou</span><br/>
<span><b>Salesforce Submit Date:</b> 10/04/2017 10:16 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Performance</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> The selection set was not notifying the editor there was a change.  Code added to upstream, downstream and isolation trace to push selection set to the editor.</span><br/>
</div></div>

**Comment by previnWong** [comment]
Attribute window is blank after the trace regardless of before or after a edit session is started.  Behavior in both 10.2.1 and 10.6

![image](https://user-images.githubusercontent.com/11183838/34585323-17502e86-f154-11e7-89b7-3c88a159fa5b.png)

**Comment by MikeMillerGIS** [comment]
Is there an active edit session?

Sent from my Verizon 4G LTE Droid

**Comment by previnWong** [comment]
Nevermind, I re-run and I see attributes now
![image](https://user-images.githubusercontent.com/11183838/34588432-d20dc6f4-f161-11e7-9eaf-da8ec0ec3a63.png)
