### ISSUE TITLE
Change operable status of a valve

### ISSUE THREAD

**Issue by Belhadjma** [Esri/local-government-desktop-addins#275]
Hi everyone,

I use the water utility network application on the local govermnent data of ESRI and everything goes well except for the tool named "**change operable status of a valve**" I got a message: Please see the screenshot below. Please help.

Note: I use Arcgis 10.5 and water utility network application June 2017

![image](https://user-images.githubusercontent.com/25690731/34005211-14ed04ce-e0f2-11e7-90e2-21fe89820642.png)

 

Thanks a lot

**Comment by MikeMillerGIS** [comment]
can you provide a copy of your config and data schema?

**Comment by Belhadjma** [comment]
[loaded.water.zip](https://github.com/Esri/local-government-desktop-addins/files/1560182/loaded.water.zip)

**Comment by Belhadjma** [comment]
for the schema I use the same as the  local govermnent data of ESRI : here is the link  http://solutions.arcgis.com/utilities/water/help/network-editing/DataDictionary/DataDictionary.Htm

**Comment by MikeMillerGIS** [comment]
if that is the case, then I am unsure.  Config file is the one we ship and with that data.  Can you ensure you have the Operable field on your valves and you can change that from true/false?  What language is your machine and arcmap running?

**Comment by Belhadjma** [comment]
Language is English for both my machine and arcmap.
![image](https://user-images.githubusercontent.com/25690731/34006400-1ae770a4-e0f6-11e7-8c1e-84254b0049bc.png)

**Comment by MikeMillerGIS** [comment]
The only time we have seen this then is there is a conflict with an old version.  Can you uninstall the Attribute Assistant and Water Editing Add in, restart ArcMap and then manually clean out the assembly cache.

%APPDATA%\ESRI\Desktop10.6\AssemblyCache
or
%LOCALAPPDATA%\ESRI\Desktop10.6\AssemblyCache

Go through each folder and if you see water and attribute assistant dlls remove that folder

Restart ArcMap and ensure the folders are not recreated
if not close ArcMap and reinstall the add ins

**Comment by Belhadjma** [comment]
Ok, thanks a lot.
 I will do that and I will feed back.

**Comment by Belhadjma** [comment]
Hi, 
I did not find  the folder named **AssemblyCache** : 


![image](https://user-images.githubusercontent.com/25690731/34008179-669d3104-e0fc-11e7-8bf5-d488d3bee914.png)

**Comment by MikeMillerGIS** [comment]
it is a hidden and protected OS folder.

**Comment by Belhadjma** [comment]
I make a seach on the whole disk drive but nothing

**Comment by MikeMillerGIS** [comment]
make sure to do this
https://www.interfacett.com/blogs/how-to-show-protected-operating-system-files-in-windows-8-and-windows-server-2012/

**Comment by Belhadjma** [comment]
Yes as you can see in the screenshot above, I have checked the hiden file.

**Comment by MikeMillerGIS** [comment]
that is different than protected os folders

**Comment by Belhadjma** [comment]
Super, I found the folder.

**Comment by Belhadjma** [comment]
I am back again. 
I've done all the steps mentionned above, but when I start my workspace space I notice that it makes changes in the config file. So repeat all the stuff again but,  this time I started a brand new MXD file and surprise it works.
So it's strange for me that my old mxd document changes the config file when I run it !!!

**Comment by MikeMillerGIS** [comment]
so all set?  If config file does not exist, it will create it

**Comment by Belhadjma** [comment]
Yes all seems to be working nice. I have to delete all my old mxd and restart new ones.

Thanks a lot for your help. I appreciate that very much.
