### ISSUE TITLE
CIP - Streets not valid configuration

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#276]
@MikeMillerGIS Seems that "Streets" is no longer a layer that is provided with the CIP data and therefore enabling costing for the Streets layer does not work. 

Should streets be removed from the config or updated to use a different feature class, such as RoadsCenterline?

**Comment by MikeMillerGIS** [comment]
Remove from config,  want me to recompile?

**Comment by MikeMillerGIS** [comment]
oh the configs is in the data, not the tools.  Lets remove it.

**Comment by clareprice** [comment]
Sounds good. Will get a new version of the download on box. Thanks for confirming!
