### ISSUE TITLE
ReleaseComObject code checks different object than it releases

### ISSUE THREAD

**Issue by psiczewicz** [Esri/local-government-desktop-addins#278]
In AttributeAssistantAddIn >  AttributeAssistantEditorExtension.cs, under case "LINK_TABLE_ASSET":  There is a line of code that checks whether 'row' is null, but then releases a different object (cCurs).

if (row != null)
   Marshal.ReleaseComObject(cCurs);
row = null;

I believe that it should be checking cCurs instead.

**Comment by MikeMillerGIS** [comment]
thanks, removed the line, as the cursor clean is handled in the finally.
