### ISSUE TITLE
BUG-000113515 Attribute Assistant - Parcel Fabric 'On-Create' event triggers update during un-join/join process

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/local-government-desktop-addins#279]
Un-joining parcel manually (keeps original OID of record) and then joining it triggers 'On-create' overwriting parcel numbers.  Reproducible with our standard Tax Parcel Editing map that we ship (FGDB source).  Reproduced on SQL Server enterprise as well.

1. Open MXD and **Start Editing**
2. Select a Tax Parcel 
3. Right click-**unjoin**
4. Right click the parcel in the **Parcel Explorer** and choose **Join**
5. Click **OK** on the join dialog
6. Examine the new parcel - new Parcel ID
<span><b>Salesforce ID:</b> [BUG-000113515](https://qamonitor/SfTriage?sfid=BUG-000113515)</span><br/>

**Comment by MikeMillerGIS** [comment]
Comments from bug
Steps:
1. Configure Attribute Assistant to auto-generate a ParcelID field with an auto-incrementing ID using the DynamicValue and GenerateID tables.

To do so, add a record in the DynamicValue table that comes with the Attribute Assistant download with the following attributes:
DynamicValue:
Table Name <ParcelFabric_Parcels>
Field Name <PARCELID>
Value Method <Generate_ID>
Value Info <PARCEL_SEQ|True>
On Create <True>
On Change (Attribute) <False>
On Change (Geometry) <False>
Manual Only <False>
Rule Weight <Null>
Comments <Null>

Also, add a record in the GererateID table that comes with the Attribute Assistant download:
GenerateID:
Sequence Name <PARCEL_SEQ>
Sequence Counter <1045167>
Interval Value <1>
Comments <Null>

2. Create a new empty file geodatabase.
3. Import the two tables that you've modifed DynamicValues and GenerateID in the new file geodatabase.
4. Create a new Feature Dataset.
6. Create a new parcel fabric named <ParcelFabric> with field <ParcelID> in the Parcels table.
7. Add the attribute assistant toolbar to your map.
8. Create a new parcel with the Attribute Assistant Turned ON. Make note of the auto-generated ParcelID value.
9. Unjoin this parcel.
10. Join this parcel.
11. Note that the ParcelID value has changed and has incremented by 1.

**Comment by MikeMillerGIS** [comment]
Traced this to pFeatChange.OriginalShape.IsEmpty.  When a parcel is unjoined and join, the original shape is empty
``` c#
 if (bIsFabricRecord)
                            {
                                if (pFeatChange.OriginalShape.IsEmpty)
                                    sendEvent(obj, "ON_CREATE"); //original shape empty, but shape change means new parcel
                                else
                                    sendEvent(obj, "ON_CHANGE");//treat geometry changes as standard change for fabric
                            }
                            else
                                sendEvent(obj, "ON_CHANGEGEO");
                        }
```
The workaround is to use the fourth parameter, this will only create an ID when the field is null:
PARCELID|0|[seq]|True

**Comment by MikeMillerGIS** [comment]
Issue on hold, waiting from response from parcel fabric team, work around is validate if the create event is required.

**Comment by MikeMillerGIS** [comment]
```xml
<!--Option to suppress stored event on all cases, only disable if experiancing issue with the parcel fabric.  May case issues with other rules-->
    <add key="SetStoreEventsRequired" value="True"/>
```

**Comment by MikeMillerGIS** [comment]
options are True | False
