### ISSUE TITLE
ENH-000114565  Give the Add Point and Laterals Tool in Water Utility Network Editing Tools the ability to recognize an existing point so connectivity rules do not cause extra data to be made.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#285]
<div><div>
<span><b>Salesforce ID:</b> ENH-000114565</span><br/>
<span><b>Salesforce Submitter:</b> Andy Shoemaker</span><br/>
<span><b>Salesforce Submit Date:</b> 6/08/2018 9:18 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> User Story:<br><br>When setting up editing tools, users wish to make creation of data as easy as possible. Within a Geometric Network, connectivity rules do this by forcing specific default junction types or laterals. This can, however, conflict with the Water Utility Network Editing tools. When the Add Point and Lateral tool is utilized, it can create 2 junctions on the end of a lateral: one when the tool is initially use and the second when the lateral is made by the tool. Adding capabilities similar to the existing &quot;DeleteExistingLine&quot; tags will address this issue. <br><br>Steps to Demonstrate:<br><br>1) Create a geometric network and add a Network Connectivity Rule which enforces a point on the end of a lateral<br>2) Modify the loaded.water.config file for the Water Utility Network Editing tools so the Add Point and Lateral Tool creates the same lateral/point combination<br>3) Load the data into ArcMap and start an edit session<br>4) Create a new lateral in the network, note that the designated junction is automatically added to the end of the lateral<br>5) Use the Add Point and Lateral tool<br>6) Identify the newly created point on the end of the junction, note that two features have been created. </span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Electric, Gas, Water and Telecommunications</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
Look at reading the rules and no create the points at start or end - https://desktop.arcgis.com/en/arcobjects/latest/net/webframe.htm#igeometricnetwork.htm

**Comment by MikeMillerGIS** [comment]
This may be complicated as what if the template is placing a point is not the point defined in the GN rules.

**Comment by LindsayThomas** [comment]
Closing to match backend support app
