### ISSUE TITLE
Update fields to blank or null 

### ISSUE THREAD

**Issue by mhammond0420** [Esri/local-government-desktop-addins#29]
Intersecting Feature Tool leaves values in the field even when feature is edited and no longer intersects. Would be nice if the field were to be reset to blank or null when no intersecting feature is found.

**Comment by MikeMillerGIS** [comment]
Fourth parameter added to Intersecting_Feature method, when True, and the field is nullable, null will be set when no intersecting feature is found.
wMain|DIAMETER|F|True

**Comment by MikeMillerGIS** [comment]
help updated
