### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#308]
## Water Network Editing and Gas Network Editing
- **Issue #304** - Improved performance of valve isolation trace when closed valve query was specified in config file.  (BUG-000113151)
- **Issue #298** - Create Lateral tool no longer generates disconnected doglegs. (BUG-000117531)
- **Issue #296** - Corrected logic used to generate arithmetic rotation. (BUG-000113365)
- **Issue #295** - Resolved issue where flags and barriers where not being drawn in the correction location in a map where the projection was different than the data. (BUG)
- **Issue #282** - Resolved issue exporting data to excel with invalid date. (BUG-000113999)

## Attribute Assistant 
- **Issue #300** - Renamed Intersect_Count rule to Intersecting_Count.  Older configurations which use Intersect_Count are still valid and will continue to work (Enhancement)
  - We need to update the solution help for this rule and change the text from Intersect_Count to Intersecting_Count and make sure we add a note that the old rule name of Intersect_Count is still valid.
  - https://solutions.arcgis.com/shared/help/attribute-assistant/documentation/methods-all-methods/#intersecting-count
- **Issue #297** - Improve list experiance on methods that present a prompt to the user. (ENH-000116271)
- ** Issue #294** - Added statics options to the copy link record method. (Enhancement)
- ** #292 ** - Resolved issue on intersect stats when the intersecting value appeared to be an exponential function, such as 1e14. (BUG)
- **#284 ** - New option added to From_Junction and To_Junction methods to evaluate flow direction instead of digitized direction to determine from or to features. (BUG-000113645)
  - Added 6th option to help doc
     - checkFlow: Option to use the flow direction to determine from and to and not digitized direction
     - Note, we need to doc also includeFCName - Option to include the name of the layer in the results, but it is currently not plumbed, so lets make a note it is reserved for future use
- **#283** - Resolve issue in expression rule when an " symbol was used. (BUG-000114270)
- **#281** - When defining multiple fields on Validate Attribute Lookup, null values are non longer used to find possible candidates. (Enhancement)
- ** #280** - Exposed new configuration option to present the comments from the dynamic value table in the prompt dialog for rules that present the option dialogs to users.  This allows you to tailor the prompt and help the end user understand what information they are selecting.
   - Need to doc a change to the AA config file, see issue for new xml entry
   - goes here https://solutions.arcgis.com/shared/help/attribute-assistant/documentation/configure-attribute-assistant/
- ** #279** - Exposed new configuration option to change the internal events.  This is required for parcel fabric workflows that Join and Unjoin parcels.  Set to False if you are using the parcel fabric.
BUG-000113515)
   -  Need to doc a change to the AA config file, see issue for new xml entry
   - goes here https://solutions.arcgis.com/shared/help/attribute-assistant/documentation/configure-attribute-assistant/
- ** #230 ** - Exposed ability to set a value instead of a field value in Create Linked Record (Enhancement)

## Capital Planning
- ** #291 ** -  Project ID is not required for selection of asset (BUG)
- ** #290 ** - Tooltip added to sketch with length of line segment (Enhancement)
- ** #289## - Selection of features for costing honors definition queries and features filtered by query are no longer loaded to the costing pane.(Bug)
- **#288** - Resolved issue where project page did not load details correctly the first time it was being accessed.  (BUG)

**Comment by ElenaFernandes** [comment]
Reminder to discuss #279 and #280 - not sure exactly how to doc but don't want to forget.

**Comment by ElenaFernandes** [comment]
Updates in pull request https://github.com/ArcGIS/arcgis-solutions-website/pull/7552 and https://github.com/ArcGIS/arcgis-solutions-website/pull/7553
