### ISSUE TITLE
My Water Utilities Reporting Tool project creates error

### ISSUE THREAD

**Issue by manya66** [Esri/local-government-desktop-addins#31]
My modified Water Utilities Reporting Toolbar, customized to our water district data, was working fine until I commented out some tools in the config.esriAddinx file. Although the project builds fine, I get the attached error message when trying to use the tools in my ArcGIS 10.2 for Desktop ArcMap application now. I tried to roll the commented out sections back in, but I'm still getting the error message.
![waterutilitiesaddinerror](https://cloud.githubusercontent.com/assets/9824374/6026444/d468633e-ab8f-11e4-97ac-ea4b4d98dfa0.JPG)

**Comment by MikeMillerGIS** [comment]
I have seen this error when the structure if the config file is not valid.  I would look for a way to validate the xml file.

**Comment by MikeMillerGIS** [comment]
Closing, reopen if you find it is a bug in the code and not a xml issue.
