### ISSUE TITLE
Compatibility with ArcGIS version?

### ISSUE THREAD

**Issue by ming800** [Esri/local-government-desktop-addins#313]
Does this addins compatible with latest ArcGIS Desktop. I updated my ArcGIS from 10.7 to 10.8.1 and suddenly, the add-in cannot be installed/extracted during the debugging. Below is the msg from the Visual Studio output window:

------------------------------------------
... ....
Could not extract Add-In file content.

Could not extract Add-In file content.

Could not extract Add-In file content.
com\ole32\ole232\stdimpl\olereg.cpp(654)\ole32.dll!77050243: (caller: 648E8428) ReturnHr(1) tid(6750) 80040154 Class not registered
com\ole32\ole232\stdimpl\olereg.cpp(654)\ole32.dll!77050243: (caller: 648E8428) ReturnHr(2) tid(6750) 80040154 Class not registered
com\ole32\ole232\stdimpl\olereg.cpp(654)\ole32.dll!77050243: (caller: 648E8428) ReturnHr(3) tid(6750) 80040154 Class not registered
com\ole32\ole232\stdimpl\olereg.cpp(654)\ole32.dll!77050243: (caller: 648E8428) ReturnHr(4) tid(6750) 80040154 Class not registered
com\ole32\ole232\stdimpl\olereg.cpp(654)\ole32.dll!77050243: (caller: 648E8428) ReturnHr(5) tid(6750) 80040154 Class not registered
'ArcMap.exe' (Win32): Unloaded 'C:\Program Files (x86)\ArcGIS\Desktop10.8\bin\ACESystemLib.dll'
'ArcMap.exe' (Win32): Unloaded 'C:\Program Files (x86)\ArcGIS\Desktop10.8\bin\ACEUtilitiesLib.dll'
'ArcMap.exe' (Win32): Unloaded 'C:\Program Files (x86)\ArcGIS\Desktop10.8\bin\ImageSupportDataLib.dll'
... ...
------------------------------------------------------------------------

Thanks, 

Ming

**Comment by MikeMillerGIS** [comment]
It is working in 10.8.1
![image](https://user-images.githubusercontent.com/2707285/98403736-700b2200-2037-11eb-9324-be758d732029.png)

**Comment by ming800** [comment]
Thanks !

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MikeMillerGIS** [comment]
hmm, I just got a crash on closing ArcMap though.

**Comment by MikeMillerGIS** [comment]
if you cannot get the add ins to installed, i would suggest logging a tech support incident.  I will try to see if the crash on shutdown is related

**Comment by ming800** [comment]
After uninstall/reinstall ArcGIS Desktop 10.8.1and ArcObjects for .Net, it works again!

**Comment by MikeMillerGIS** [comment]
nice!
