### ISSUE TITLE
Attribute assistant toggle

### ISSUE THREAD

**Issue by faridcher** [Esri/local-government-desktop-addins#33]
When working in Arcmap, suddenly I get this error,

Error setting AA Toggle button: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

please help.

**Comment by MikeMillerGIS** [comment]
What version of the tools are you using?  What are you doing when this happens?  When does it occur?

**Comment by faridcher** [comment]
It happens accidentally. Even when Arcmap is idle (e.g. I am not working with Arcmap). I use the latest version.
The problem is from the AttributeAssistantEditorExtension.setIcon()  method. To be more specific it is from this line::

commandItem.FaceID = ESRI.ArcGIS.ADF.COMSupport.OLE.GetIPictureDispFromBitmap(bmpOn);

But I don't know what can be  the reason. I'll debug it when I have the time.

**Comment by MikeMillerGIS** [comment]
I added some additional try/catch blocks around it and removed the msgbox with the error.  So if it happens, it will be supressed.

**Comment by MikeMillerGIS** [comment]
Closing, please reopen if after the next release it comes back.
