### ISSUE TITLE
BUG-000086127  Add Site Address Point construction tool generates incorrect address values on one side of the road beyond 400ft.

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/local-government-desktop-addins#38]
<div><div>
<span><b>Salesforce ID:</b> BUG-000086127</span><br/>
<span><b>Salesforce Submitter:</b> Kara Manseau</span><br/>
<span><b>Salesforce Submit Date:</b> 3/16/2015 2:37 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Salesforce Attachments:</b> AddSiteAddressPtTool.mpk, workflowvideo.mp4</span><br/>
<span><b>Salesforce Attachments Location:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000086127</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000086127</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Heather\Scott\Lindsay has reviewed this issue and are able to reproduce this issue.</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
Heather was able to reproduce this issue. It only seems to happen when adding a site address point about 450 feet North of the road (does not occur when add south of the line regardless of distance).

@HeatherEisan Anything you wanted to add?

**Comment by MikeMillerGIS** [comment]
The hard coded search threshold is 400 map units.  We can expose this in the config or make it something really large.  Please advise which way you want to proceed.
@LindsayThomas @HeatherEisan @ScottOppmann

**Comment by MikeMillerGIS** [comment]
Fix Installed

**Comment by LindsayThomas** [comment]
@HeatherEisan Can you verify this issue for the June Release.

**Comment by HeatherEisan** [comment]
Verified. Tested on ArcGIS version 10.3.1 & 10.3, and Address Data Management and Attribute Assistant Add-in version 6.26.2015.
