### ISSUE TITLE
SQL and Oracle – New methods to ensure Generate ID works

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/local-government-desktop-addins#40]
This needs testing against SQL and Oracle – New methods to ensure Generate ID works.  

https://github.com/Esri/local-government-desktop-addins/commit/91143949a2c85ac394125a0ffc1ecbfe991a0ce7

@MikeMillerGIS Added this as an issue to test for the June 2015 release
@clareprice

**Comment by clareprice** [comment]
Tested for June release
