### ISSUE TITLE
Spelling mistakes in the Loaded.config file

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/local-government-desktop-addins#46]
@MikeMillerGIS Please fix the following spelling mistakes in the Loaded.config file.

- dependecy (dependency)
![image](https://cloud.githubusercontent.com/assets/2781011/7458889/e7e89f88-f24c-11e4-870d-e7231ae1c2ba.png)

- Tolerace (Tolerance)
![image](https://cloud.githubusercontent.com/assets/2781011/7458894/ff9ca44e-f24c-11e4-8598-4353c7efd527.png)

- staus (status)
![image](https://cloud.githubusercontent.com/assets/2781011/7459147/c7166b76-f24e-11e4-9a1c-4b9c989d5f5c.png)

- xml (XML)

![image](https://cloud.githubusercontent.com/assets/2781011/7459322/e8091940-f24f-11e4-8cc9-6314cde4e49f.png)

![image](https://cloud.githubusercontent.com/assets/2781011/7459018/d41a97e4-f24d-11e4-8b40-3b26956f62f0.png)

- zooom (zoom)
![image](https://cloud.githubusercontent.com/assets/2781011/7459169/f51e0d62-f24e-11e4-8e3a-16fef263b800.png)

![image](https://cloud.githubusercontent.com/assets/2781011/7459516/6b0f4e4e-f251-11e4-982b-c752c241efe4.png)

![image](https://cloud.githubusercontent.com/assets/2781011/7459173/fb897e02-f24e-11e4-84a5-642851d90537.png)

- directon (direction)
![image](https://cloud.githubusercontent.com/assets/2781011/7459032/efb6e5f2-f24d-11e4-8cd0-989c45021f8a.png)

- beteen (between)
![image](https://cloud.githubusercontent.com/assets/2781011/7459044/05e3360a-f24e-11e4-9681-37031c237b14.png)

- secions (sections)
![image](https://cloud.githubusercontent.com/assets/2781011/7459078/524b4ed8-f24e-11e4-82e8-5bebc371a06a.png)

![image](https://cloud.githubusercontent.com/assets/2781011/7459556/c25b8104-f251-11e4-83e4-be92ee47d2c1.png)

- sqaure (square)
![image](https://cloud.githubusercontent.com/assets/2781011/7459255/7f0690a8-f24f-11e4-9bab-03d7f467b2c2.png)

- configuartions (configurations)
![image](https://cloud.githubusercontent.com/assets/2781011/7459097/7f924496-f24e-11e4-8c99-233c515f8353.png)

- closests (closest)
![image](https://cloud.githubusercontent.com/assets/2781011/7459110/9550175e-f24e-11e4-97e7-bf064f0a17f2.png)

**Comment by MikeMillerGIS** [comment]
resolved and closed
