### ISSUE TITLE
BUG-000089019  When running the second time "Run Manual Change rules for selected features" after selecting "No" when prompted if it should run on the selected features, the attribute assistant toolbar cannot be run.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#52]
<div><div>
<span><b>Salesforce ID:</b> BUG-000089019</span><br/>
<span><b>Salesforce Submitter:</b> Matthew Patterson</span><br/>
<span><b>Salesforce Submit Date:</b> 7/13/2015 8:22 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> High</span><br/>
<span><b>Salesforce Attachments:</b> AddressDataManagement.zip, ManualRulesBroke.mp4</span><br/>
<span><b>Salesforce Attachments Location:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000089019</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000089019</span><br/>
<span><b>Work Around:</b> Close and open arcmap.
Or only select 1 feature.</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> Windows 7</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
Hotfix requested (this will be in the next major release as well) 

Verifying compiled version now

**Comment by skrishn** [comment]
@MikeMillerGIS @LindsayThomas Verified.

**Comment by LindsayThomas** [comment]
@skrishn can you make a not on the versions verified please.

**Comment by skrishn** [comment]
@LindsayThomas @MikeMillerGIS 

Tested add-in version (7.16.2015) on 10.1 SP1 QIP, 10.2.1, 10.2.2 and 10.3.1. 

In 10.2.2 - Tested workflow for all add-ins (AddreddManagement, ArcGISCostEstimatingTools, AttributeAssistant,WaterUtilityNetworkTools) in 
Water Utility Editing
Address Data Management
Capital Improvement Planning
