### ISSUE TITLE
ENH-000088863  Provide an option for Attribute Assistant's Intersecting Feature method to automatically use the polygon which has the highest intersection length with the input line, when the input line intersects multiple polygon features.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#53]
<div><div>
<span><b>Salesforce ID:</b> ENH-000088863</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 7/06/2015 10:38 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> 1. What is the industry?<br>Customer #440286 is an urban Local Government around 200.000 inhabitants<br><br>2. What is the user&#39;s workflow and use case?<br>Water distribution network collection with ArcMap.<br><br>3. What is the problem that this software functionality would solve?<br>It would help automate attribute transfer from Road network and zoning to water distribution line features.<br><br>4. What are the benefits or changes that would result from the enhancement?<br>It would increase productivity and database quality<br><br>5. How critical is the enhancement to your organization?<br>Medium -high<br><br>6. How do you believe this enhancement may benefit other organizations?<br>It would give more options and flexibility to Attribute assistant<br><br>7. How many users are affected?<br>5 users<br><br>*** I pointed out out that the Prompt option could be used [P (Prompt for search method)] which will show the user the options based on which polygons the line feature intersects. The user then selects the correct one.  The customer is asking specifically for an option that will automatically use attributes from the polygon where the intersection length is longest.*** <br><br> </span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> Windows 7</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by LindsayThomas** [comment]
closed on the backend updating to match the support app
