### ISSUE TITLE
Valve Isolation Trace

### ISSUE THREAD

**Issue by faridcher** [Esri/local-government-desktop-addins#61]
Please somebody explain how exactly trace isolation tool works (or is supposed to work)? please clarify how it uses the parameters? 
I have already looked into the online documentation
http://solutions.arcgis.com/utilities/water/help/network-editing/tools/overview-reporting-tools/

**Comment by MikeMillerGIS** [comment]
I would suggest downloading the Water Utility Network Editing solution and see how the tool performs.

http://solutions.arcgis.com/utilities/water/help/network-editing/

**Comment by faridcher** [comment]
I have already done that. Tools like valve isolation trace, needs detailed  documentation and clarification of their behavior.  something like:

The trace starts from click position and it stops once an open or close valve is reached. The open valves are returned as the result of the trace and blah blah blah.
