### ISSUE TITLE
Generate ID: Overwrite Blank

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#65]
Currently, the Generate ID method allows for the option to overwrite the ID field is triggered when the field is null. Enhancement to overwrite the id if the field is blank or null.

@MikeMillerGIS

**Comment by MikeMillerGIS** [comment]
Fixed added in 
https://github.com/Esri/local-government-desktop-addins/commit/5ba9c05b0407482e64b6fd7fa4ca4747c9364e43
