### ISSUE TITLE
Valve Isolation Trace Source Layer 

### ISSUE THREAD

**Issue by faridcher** [Esri/local-government-desktop-addins#68]
I got a headache to understand your TraceIsolation method! I suggest to rewrite this huge function. however I think there are serious bugs in the code. I commented out some parts of the code and I think it works fine now. Please check and verify and then I will request a pull request.
Line: 5193:

                if (sourceEIDInfoHT.Count == 0)
                {
                    if (processEvent)
                    {

                        pStepPro.Message = A4LGSharedFunctions.Localizer.GetString("No") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_15c") + Environment.NewLine +
                         Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16b") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16c") + Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsProc_16j");
                        MessageBox.Show(pStepPro.Message);
                        pStepPro.Step();
                        boolCont = pTrkCan.Continue();
                    }

                    if (!boolCont)
                    {

                        pStepPro.Hide();
                        pProDlg.HideDialog();
                        pStepPro = null;
                        pProDlg = null;
                        pProDFact = null;
                        return null;
                    }
                    return A4LGSharedFunctions.Localizer.GetString("Error") + A4LGSharedFunctions.Localizer.GetString("No") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_15c") + Environment.NewLine +
                         Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16b") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16c") + Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsProc_16j");
                }

and Line 5359:

                if (sourceEIDInfoHT.Count == 0)
                {
                    if (processEvent)
                    {

                        pStepPro.Message = A4LGSharedFunctions.Localizer.GetString("No") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsProc_16o") + Environment.NewLine +
                         Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16b") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16c") + Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsProc_16j");
                        MessageBox.Show(pStepPro.Message);
                        pStepPro.Step();
                        boolCont = pTrkCan.Continue();
                    }

                    if (!boolCont)
                    {

                        pStepPro.Hide();
                        pProDlg.HideDialog();
                        pStepPro = null;
                        pProDlg = null;
                        pProDFact = null;
                        return A4LGSharedFunctions.Localizer.GetString("CanceledReturnStatement");
                    }
                    return A4LGSharedFunctions.Localizer.GetString("Error") + A4LGSharedFunctions.Localizer.GetString("No") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsProc_16o") + Environment.NewLine +
                         Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16b") + sourceFLName + A4LGSharedFunctions.Localizer.GetString("GeoNetToolsMess_16c") + Environment.NewLine +
                         A4LGSharedFunctions.Localizer.GetString("GeoNetToolsProc_16j");
                }

**Comment by MikeMillerGIS** [comment]
Can you explain what error this code was causing?  The current code base has a lot of implementations without issue.

**Comment by faridcher** [comment]
Nothing happens. The progress dialog appears and closes and no result is returned. While debugging 

(sourceEIDInfoHT.Count == 0) or (sourceEIDInfoHT.Count == 0)

conditions are met and therefor the progress finishes immaturely. Although there are source features reachable from the click point.

**Comment by MikeMillerGIS** [comment]
The trace requires a valid source of water to work correctly(tank, clear well, etc).  This ensures the proper results and dead ends are included.

Sent from my Verizon Wireless 4G LTE DROID

**Comment by faridcher** [comment]
In the case, I have source feature (Regulator Gas Stations) in my network, the original code doesn't work.

 In addition, we have situations that no source feature is accessible from trace point. e.g. tracing a distribution branch that is bounded by just valves.

**Comment by MikeMillerGIS** [comment]
Then there is a connectivity issue.  The trace requires a source as it first does a find connected from the flag.  This returns the first set of valves.  It loops through each valve, placing barriers at all the other valves, and does a find path to the sources.  If no source can be reach, the valve is not required to be closed and removed from the trace(like a valve in a dead end).  So for this trace to work, a connect source is required on the network.

**Comment by faridcher** [comment]
Thanks Mike. The problem was not from connectivity. Now I understand the way this tool works. make sure to include the tool behavior somewhere (help docs) or tooltip.
