### ISSUE TITLE
Remove duplicates in INTERSECT_STATS

### ISSUE THREAD

**Issue by SASrinivas** [Esri/local-government-desktop-addins#69]
Please provide an option to exclude duplicating values. Following is an example.

![image](https://cloud.githubusercontent.com/assets/9484194/10003359/d5a6b10c-6060-11e5-8237-0e29626d255c.png)

Should be
![image](https://cloud.githubusercontent.com/assets/9484194/10003412/12156d5e-6061-11e5-8cf8-9c8dee854536.png)

**Comment by MikeMillerGIS** [comment]
This was a regression when we added sorting.  I resolved the issue.

**Comment by MikeMillerGIS** [comment]
will be included in the 10.4 release
