### ISSUE TITLE
Attribute Assistant is unable to apply rules and update parcel fabric records when GlobalID field is present

### ISSUE THREAD

**Issue by pavezina** [Esri/local-government-desktop-addins#71]
At line 2548 of the “AttributeAssistantEditorExtension.cs”

…
if (pFLyr != null) //make sure there's at least one valid fabric feature layer
{
       	int iObjClassID = inObject.Class.ObjectClassID;
              ITable InMemTable = AAState._fabricInMemTablesLookUp[iObjClassID];
              IRowBuffer pRowBuff = InMemTable.CreateRowBuffer();
              IFields pIncomingFlds = inObject.Fields;
              for (int i = 0; i < pIncomingFlds.FieldCount; i++)
              	{
                     IField pFld = pIncomingFlds.get_Field(i);
2548:                     if (pFld.Type == esriFieldType.esriFieldTypeOID || pFld.Type == esriFieldType.esriFieldTypeGeometry)
                     	continue;
object val = inObject.get_Value(i);
                     pRowBuff.set_Value(i, val);
                     }
	…

I think it’s missing the check for the GlobalID. If this is not there, you get an error message that “Field is not Editable”.

if (pFLyr != null) //make sure there's at least one valid fabric feature layer
{
       	int iObjClassID = inObject.Class.ObjectClassID;
              ITable InMemTable = AAState._fabricInMemTablesLookUp[iObjClassID];
              IRowBuffer pRowBuff = InMemTable.CreateRowBuffer();
              IFields pIncomingFlds = inObject.Fields;
              for (int i = 0; i < pIncomingFlds.FieldCount; i++)
              	{
                     IField pFld = pIncomingFlds.get_Field(i);
2548:                     if (pFld.Type == esriFieldType.esriFieldTypeOID || pFld.Type == esriFieldType.esriFieldTypeGeometry || pFld.Type == esriFieldType.esriFieldTypeGlobalID)
                     	continue;
object val = inObject.get_Value(i);
                     pRowBuff.set_Value(i, val);
                     }
	…

**Comment by MikeMillerGIS** [comment]
Thanks, I added it and it will be included in the next release

**Comment by MikeMillerGIS** [comment]
Will be delivered in the 10.4 release
