### ISSUE TITLE
ENH-000091413  Include more description and visual examples of input and expected output in the Attribute Assistant documentation to help users understand how to correctly configure methods and what a method's expected output is.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#73]
<div><div>
<span><b>Salesforce ID:</b> ENH-000091413</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 10/14/2015 3:38 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Documentation</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> In this particular case, the user was interested in possibly working with either the Validate Attributes or Validate Attribute Lookup methods.  The current documentation doesn&#39;t provide enough examples of input and expected output for the user to understand whether either of these methods would work for her, and if so, which one.<br>Taking Validate Attributes (<a href="http://solutions.arcgis.com/state-government/help/special-event-planning/tools/attribute-assistant-methods/#valid-attribute" target="_blank">http://solutions.arcgis.com/state-government/help/special-event-planning/tools/attribute-assistant-methods/#valid-attribute)</a> as an example, at the top of the documentation page, the method is described as, &quot;<span style="background-color: rgb(255, 255, 255); color: rgb(77, 77, 77); float: none; text-align: left; white-space: normal;">Compares values in the input fields to all feature templates for the feature class.&quot;  It is easy for a user to overlook or not understand that this method is working with a feature class&#39; feature templates, because when they go to the example given in the anchor link (</span><a href="http://solutions.arcgis.com/state-government/help/special-event-planning/tools/attribute-assistant-methods/#valid-attribute" target="_blank">http://solutions.arcgis.com/state-government/help/special-event-planning/tools/attribute-assistant-methods/#valid-attribute)</a> feature templates are not mentioned again.  If there is not a default value set up for a field in the feature template, it doesn&#39;t appear that this method does anything, leaving the user uncertain whether there is a problem with how they configured the method in the DynamicValue table. In this particular example, it would be helpful to include wording in the documentation that points out that a feature template needs to be set up with values to validate against.<br>As an example, &quot;To configure this method, ensure that a feature template is configured for the feature class.  The feature template must include a default value for the field against which the Validate Attributes method will validate against... Then populate the following in the DynamicValue table:&quot;<br><br>Including more visual examples showing correct setups for each method would improve the usability for customers. <br><br><br> </span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> Windows 7.0 64 Bit</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Enhancement logged to add additional doc</span><br/>
</div></div>

**Comment by pLeBlanc93** [comment]
Adding documentation.
