### ISSUE TITLE
How to generate sequence number by Grid for Generate_ID_From_Grid method in Attribute Assistant add-in

### ISSUE THREAD

**Issue by lesleyroddam** [Esri/local-government-desktop-addins#75]
I want to number my water valves by grid # followed by an incrementing number *for each grid*. Is this possible with the Generate_ID_From_Grid method in the Attribute Assistant add-in? It seems that only one number counter can apply regardless of which grid the valve intersects. I need the valves to be number 1 thru n for each grid. Help?!

**Comment by MikeMillerGIS** [comment]
This geonet thread may help you out.
https://geonet.esri.com/thread/62327

here is the help
http://solutions.arcgis.com/shared/help/attribute-assistant/tools/attribute-assistant-methods/#generate-id-intersect

**Comment by lesleyroddam** [comment]
Thank you, Mike. The "help" file doesn't answer my question, but I will look at the other link you provided.
