### ISSUE TITLE
Is a table prefix a problem for Attribute Assistant?

### ISSUE THREAD

**Issue by lesleyroddam** [Esri/local-government-desktop-addins#76]
My water features are in an Oracle SDE database. The database is referred to as "wat" (that's the owner) and the water features life in a feature dataset called "WAT.Water". When I copied the GenerateID and DynamicValue tables into the "wat" connection, they were automatically called "WAT.DynamicValue" and "WAT.GenerateId". As well, my features are called "WAT.Hydrant" and "WAT.SystemValve", for example. So when I customize the DynamicValue and GenerateID tables and modify the Loaded.config file, should I set these tables and features to have the WAT. prefix? I can't get anything in Attribute Assistant to fire and am trying to figure out why. Thank you!

**Comment by MikeMillerGIS** [comment]
Those prefixes are not required.  The code removes the database and owner name.

**Comment by lesleyroddam** [comment]
Thank you for clarifying! I verified that Attribute Assistant is firing by running the "Current_User" method on the ValveNumber attribute of the SystemValve feature (just as a test). But I can't get the Generate_ID_By_Intersect method to do anything no matter what variation of values I input into the Value Info field. My eventual goal is to have it create a valve number starting with "V", then the intersecting grid number, then the next number available in that particular grid. As a baby step before going there, I tried just using an existing sequence number and put "OUC_WATER_GRID|GRIDNUM|WHYDRANT|3|V-[ID]-[SEQ]" in the Value Info field but the ValveNumber field comes out <null> when I put in a new SystemValve. Any thoughts? (Going home now, will pick back up Monday.) Thank you!

**Comment by MikeMillerGIS** [comment]
There is a log file that you can turn on and that will help trouble shoot what is happening

**Comment by MikeMillerGIS** [comment]
http://solutions.arcgis.com/shared/help/attribute-assistant/tools/configure-attribute-assistant/

Search for log file

**Comment by lesleyroddam** [comment]
I set the AttributeAssistant_Debug key value to "True" and tried both leaving the AttributeAssistant_Debug_Path alone so it would write to the default location and setting it to "C:\temp", but it never creates a log file. It poplates a ValveNumber if I use the Generate_ID method, but not the Generate_ID_By_Intersect method. I've tried many variations in the Value Info field but the ValveNumber always comes out <null>, and no log file is written. My intersecting polygon feature class is in my mxd, and the valves I create fall within one of my polygons. Can you think of any common mistakes with this method that might be my problem?

**Comment by MikeMillerGIS** [comment]
If you open the attribute assistant toolbar, can you find the log there?

**Comment by lesleyroddam** [comment]
Thank you! Well, that answers why I couldn't find the log file! Though I set it to "C:\temp" it was still using the default location, which I thought was C:\Users\roddl128\AppData\Roaming\ArcGISSolutions, but was really C:\Users\roddl128\ArcGISSolutions. I didn't realize I could open the log file from the Attribute Assistant toolbar - thanks for that, too. And now I know what was going wrong and it's working now. I appreciate your help.
