### ISSUE TITLE
Junction_Rotation: one junction feature but multiple source features for angle?

### ISSUE THREAD

**Issue by lesleyroddam** [Esri/local-government-desktop-addins#77]
I have a SystemValve feature on which I want to run the Junction_Rotation method to pick up the angle of both my MainLine and ServiceLine features, whichever one we are connecting to. Can this be possible? Thanks!

**Comment by MikeMillerGIS** [comment]
Yes, just do not define the last option(source)
http://solutions.arcgis.com/shared/help/attribute-assistant/tools/attribute-assistant-methods/#junction-rotate

**Comment by lesleyroddam** [comment]
Thank you, I misunderstood the explanation in the documentation! This is great.
