### ISSUE TITLE
Can Junction_Rotation work when placing feature at end of line?

### ISSUE THREAD

**Issue by lesleyroddam** [Esri/local-government-desktop-addins#78]
The Junction_Rotation method is working for my Fittings and Valves if I snap them onto a MainLine or ServiceLine somewhere between the two endpoints. However, if I snap the Fitting or Valve onto the endpoint of the MainLine or ServiceLine, it sets the angle of the point feature to zero.

**Comment by MikeMillerGIS** [comment]
I cannot repro this issue, what does the log file say?
![image](https://cloud.githubusercontent.com/assets/2707285/10821783/8aaea67c-7e2a-11e5-8b99-1629a6e232f7.png)

**Comment by lesleyroddam** [comment]
The row in my DynamicValue table is:
FITTING, ROTATION, JUNCTION_ROTATION, G

Log file for fitting placed along the line (which is working):
Row Info
        Row Number 3
        TableName: FITTING
        FieldName: ROTATION
        ValueInfo: G
        ValueMethod: JUNCTION_ROTATION
        On Create: 1
        On Change: 1

      Checking for Subtype Restriction
      Field Name: ROTATION was found at index: 5
                  Trying: JUNCTION_ROTATION
                  esriRotateSymbolGeographic is being used
                  Rotation Angle set to: 299.4906
                  Rotation Angle set
                  Finished: JUNCTION_ROTATION

Log file for Fitting placed at the end of the line (which is not working):
      Row Info
        Row Number 3
        TableName: FITTING
        FieldName: ROTATION
        ValueInfo: G
        ValueMethod: JUNCTION_ROTATION
        On Create: 1
        On Change: 1

      Checking for Subtype Restriction
      Field Name: ROTATION was found at index: 5
                  Trying: JUNCTION_ROTATION
                  esriRotateSymbolGeographic is being used
                  Rotation Angle set to: 0
                  Rotation Angle set
                  Finished: JUNCTION_ROTATION
![rotation](https://cloud.githubusercontent.com/assets/15218760/10822300/eeaabb82-7e2c-11e5-8a41-465468f7be72.JPG)

**Comment by lesleyroddam** [comment]
I'm sorry I gave you the log file for fittings, but the picture shows valves. However, they are both doing the same thing. The row in the DynamicValue table for the valves is:
SYSTEMVALVE, ROTATION, JUNCTION_ROTATE, G|90||
because I want to add 90 degrees to those symbols.
When I place either a valve or a fitting along the line, it rotates as it should (with the additional angle if provided); if I place either at the end of the line, it sets the angle to zero for fittings which have no additional angle parameter, and to 90 for valves which have the additional angle parameter set to 90, rather than to the angle of the line.

**Comment by lesleyroddam** [comment]
So this is REALLY weird. I just put two new service lines in and when I snapped a valve onto the ends of them, the valves rotated! But then I snapped a valve onto a service line that was already in my data, and it didn't rotate the valve.  ???
![rotation2](https://cloud.githubusercontent.com/assets/15218760/10823555/8eca9254-7e32-11e5-8d69-c767e6d3acd5.JPG)
