### ISSUE TITLE
Support Block spacing for addressing

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#79]
ability to assign address ranges based on an interval. In rural areas they use a 52’ interval between address numbers on a street segment. In urban areas they use an interval as small as 5.2’ and also use other intervals such as 10’ or 20’ in moderately densely populated areas. Currently they break out the calculator and say a segment in a dense urban area is 500’ long and is the 800 block. The even-numbered side of the street would be 800-898 (500/5.2 rounded up). In a rural area a 500’ long 800 block would be numbered 800-810. They use the intervals to prevent running out of new addresses between existing addresses.

**Comment by chris-fox** [comment]
We documented this as a [workflow](http://solutions.arcgis.com/local-government/help/address-management/workflows/use-logical-block-addressing/) in the June Release of Address Data Management. This leverages attribute assistant rules to calculate the LeftTo and RightTo addresses from an LBA value and the LeftFrom and RightFrom addresses.
