### ISSUE TITLE
ENH-000093876  Enhance the <CreatePointWithReference> functionality for the Address Data Management solution to allow a user to map multiple fields from the RoadCenterline feature class to the SiteAddressPoint feature class.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#90]
<div><div>
<span><b>Salesforce ID:</b> ENH-000093876</span><br/>
<span><b>Salesforce Submitter:</b> Kory Kramer</span><br/>
<span><b>Salesforce Submit Date:</b> 1/29/2016 8:04 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> 1. Provide the appropriate/comparable step by step workflow to help illustrate the request.<br>See enhancement description.<br>Currently, creating  a site address point will only populate the Full Road Name and Full Address. There is no way to configure mapping from other fields in the RoadCenterline feature class to the SiteAddressPoint feature class by using the &lt;CreatePointWithReference&gt; section in the Loaded.config file.<br><br>2. What is the problem feature X is trying to solve? (i.e. What is the problem/limitation/design choice that is preventing the customer from moving forward?)<br>With one click, when a Site Address Point is created, populate all fields from the RoadCenterline feature class into the corresponding fields of the SiteAddressPoint feature class.  This would include fields such as Prefix, Prefix Direction, StreetType, Suffix, Suffix Direction, etc.<br><br>3. What are the benefits or changes that would result from the enhancement? (i.e. How does making this change help the customer&#39;s workflow or business?)<br>This would avoid the need to set up multiple rules in the DynamicValue table for use in Attribute Assistant. <br>The current way to accomplish this is to first set up the Intersecting_Feature method to populate AddressPoint fields from the RoadCenterline that the point intersects.<br>Then the Copy_Linked_Records method can be used to work through the relationship class AddressPointHasSiteAddresses to populate the necessary fields.  In this case, all of the fields that are needed to be populated in SiteAddressPoints need to be added to the AddressPoint feature class which in terms of data storage is inefficient, yet necessary if using this workflow to populate Site Address Point fields.<br><br>4. How critical is the enhancement to the organization?<br>Not critical, but would be extremely helpful in increasing efficiency manyfold.<br>5. How do you believe this enhancement may benefit other organizations? Any organization that uses the Address Data Management solution and the Add Site Address Point tool would benefit from this.</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> Windows 7.0 64 Bit</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Enhancement added</span><br/>
</div></div>

**Comment by chris-fox** [comment]
Rather than adding multiple fields to the config we added the ability to specify the Centerline ID field from the street centerlines and a field to write the centerline id to in the site address point table. With this relationship you can then use one or more Copy_Linked_Records attribute assistant rules to populate the site addresses point layer with values from the related street centerline.

**Comment by MikeMillerGIS** [comment]
Fix deployed as part of 6-14-2016 add in
