### ISSUE TITLE
BUG-000093886  The Get Address Using ArcGIS Service method for Attribute Assistant fails to return results when the geocode service is in a Projected Coordinate System.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#91]
<div><div>
<span><b>Salesforce ID:</b> BUG-000093886</span><br/>
<span><b>Salesforce Submitter:</b> Scott Harris</span><br/>
<span><b>Salesforce Submit Date:</b> 1/29/2016 10:53 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\BUG-000093886</span><br/>
<span><b>Work Around:</b> Reference a geocode service that is in a Geographic Coordinate System.</span><br/>
<span><b>Product:</b> ArcGIS for Local Government</span><br/>
<span><b>Functional Category:</b> ArcGIS for Local Government</span><br/>
<span><b>Client Platform:</b> Windows 7</span><br/>
<span><b>Version Found:</b> 10.2</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Issue found and resolved.</span><br/>
</div></div>

**Comment by MikeMillerGIS** [comment]
https://github.com/Esri/local-government-desktop-addins/commit/91b17839c13c2113501142f9b9f0b146a8871968

**Comment by LindsayThomas** [comment]
Added support for Projected Coordinate System’s when using the “Get Address Using Geocoder” method.

**Comment by MikeMillerGIS** [comment]
Fix deployed as part of 6-14-2016 add in
