### ISSUE TITLE
Enhacement - Calculate valve, hydrant, and customer count for isolation trace

### ISSUE THREAD

**Issue by clareprice** [Esri/local-government-desktop-addins#92]
@MikeMillerGIS As discussed with @JChannin, ehnacement to automatically populate the number of valves, hydrants, and customers in the outage detail layer (created in_memory) before sharing the results.

**Comment by MikeMillerGIS** [comment]
Added support for the AA 
https://github.com/Esri/local-government-desktop-addins/commit/3f96ae336d4f8a5f25c03d953a6e0d216892e3e6

**Comment by MikeMillerGIS** [comment]
Comments from Clare and Jason are we should proceed with config params
Like this
OutageResults
                LayerToField field=VALVECOUNT layer=System Valves
                LayerToField field=HYDRANTCOUNT layer=Hydrants
                LayerToField field=CUSTCOUNT layer=Customers

**Comment by MikeMillerGIS** [comment]
@clareprice new config sections added
<AddResultsAsLayersOptions>
    <ResultCountToFields>
      <ResultCountToField>
        <FeatureClassName>wServiceConnection</FeatureClassName>
        <TargetField>CUSTOUT</TargetField>
      </ResultCountToField>
      <ResultCountToField>
        <FeatureClassName>wSystemValve</FeatureClassName>
        <TargetField>NUMVALVES</TargetField>
      </ResultCountToField>
      <ResultCountToField>
        <FeatureClassName>wHydrant</FeatureClassName>
        <TargetField>NUMHYDS</TargetField>
      </ResultCountToField>
    </ResultCountToFields>
  </AddResultsAsLayersOptions>
