### ISSUE TITLE
Enhancement - Intersect Count not in the domain for the value method

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/local-government-desktop-addins#96]

**Comment by MikeMillerGIS** [comment]
Also add the following methods:

TRIGGER_UPDATE_FROM_EDGE
TRIGGER_UPDATE_TO_EDGE
TRIGGER_UPDATE_INTERSECTING_FEATURE
TRIGGER_UPDATE_TO_JUNCTION
TRIGGER_UPDATE_FROM_JUNCTION

**Comment by MikeMillerGIS** [comment]
UPDATE_FROM_EDGE_FIELD
UPDATE_FROM_JUNCTION_FIELD
UPDATE_TO_EDGE_FIELD
UPDATE_TO_JUNCTION_FIELD

**Comment by MikeMillerGIS** [comment]
INTERSECTING_BOOLEAN

**Comment by ScottOppmann** [comment]
Added to June 2016 LGIM release.

**Comment by MikeMillerGIS** [comment]
TRIGGER_UPDATE_INTERSECTING_FEATURE rule renamed to TRIGGER_AAEVENT_INTERSECTING_FEATURE

**Comment by MikeMillerGIS** [comment]
TRIGGER_UPDATE_TO_JUNCTION
TRIGGER_UPDATE_FROM_JUNCTION
renamed to 

TRIGGER_AAEVENT_FROM_JUNCTION and TRIGGER_AAEVENT_TO_JUNCTION

**Comment by MikeMillerGIS** [comment]
TRIGGER_UPDATE_FROM_EDGE
TRIGGER_UPDATE_TO_EDGE
renamed
TRIGGER_AAEVENT_TO_EDGE and TRIGGER_AAEVENT_FROM_EDGE

**Comment by MikeMillerGIS** [comment]
TRIGGER_xxx rules provide a method to trigger the AA event on an intersecting or connected network feature.  The value method for the for the Edge and Junctions is just the type of rule to run, CREATE, CHANGEGEO, CHANGE, for the intersecting feature version it is the layername the type of rules

layer1,layer2|CHANGE for example for intersecting version
CHANGE for the JUNCTION EDGE versions

**Comment by ScottOppmann** [comment]
Updates made to June 2016 LGIM and verified.

**Comment by MikeMillerGIS** [comment]
@pLeBlanc93 @clareprice Please verify when packaging
